#!/usr/bin/env python3
"""Insert careGuideDeep blocks into the top-30 species entries in speciesDb.ts.

For each (id, deep_guide) pair, finds the species's block and inserts
careGuideDeep right after careGuide. Idempotent: if careGuideDeep already
exists for that species, skips.

No em-dashes in any string. Periods, commas, colons, parentheses only.
"""

import re
import sys
from pathlib import Path

DEEP_GUIDES = {
    'monstera-deliciosa': {
        'light': "Bright indirect light, ideally 1.5 to 2 metres from an east or north-facing window (south-facing in the southern hemisphere). Tolerates a few hours of gentle morning sun but afternoon direct light scorches leaves and bleaches the variegation if any. In dim corners growth slows and new leaves emerge without fenestrations (the holes); if no new splits appear over 3 months, light is the likely culprit. Rotate the pot a quarter turn each watering so growth stays balanced.",
        'water': "Wait until the top 3 to 4 cm of soil is dry, then water deeply until you see drainage at the bottom of the pot. In a 20 cm pot that is roughly 240 ml in growing months, dropping to 160 ml in winter. Empty the saucer within 30 minutes: standing water is the fastest path to root rot, the number-one killer of Monsteras. Yellow leaves with brown soft spots mean overwatered; brown crispy edges with droopy stems mean underwatered or low humidity. Use room-temperature water; cold tap water shocks tropical roots.",
        'food': "Half-strength balanced liquid feed (10-10-10 or 20-20-20 diluted) once every 4 weeks from October through March in the southern hemisphere (April to September up north). Skip entirely during dormancy: feeding a sleeping plant burns the roots. Slow-release pellets work too if you prefer hands-off: a teaspoon scattered on the soil in early spring lasts 3 months. Flush the pot with plain water every 2 to 3 months to wash out salt buildup that can scorch leaf tips.",
        'season': "Peak growth October to March: expect a new leaf every 4 to 6 weeks if happy. Slows dramatically May to August: extend watering intervals by 30 percent and stop feeding entirely. A moss pole or coir totem encourages bigger, more deeply-fenestrated mature leaves; without one the plant stays in juvenile form. Wipe leaves with a damp cloth monthly; dust shades them more than people realise. Repot every 2 to 3 years in early spring, up one pot size, into a chunky aroid mix (orchid bark, perlite, coconut coir).",
        'trouble': "Yellow leaves with mushy stems: overwatered, the most common killer. Let soil dry fully, trim any black roots, repot in fresh chunky mix. Brown crispy leaf edges: low humidity (below 40 percent) or salt buildup. Aim for 50 to 60 percent humidity and flush the pot quarterly. No fenestrations on new leaves: not enough light or the plant is still juvenile (under 2 years). Spider mites in winter when heating dries the air: rinse leaves in the shower, treat with neem oil weekly for 3 weeks. Aerial roots are normal: bury them in the soil or train them up a moss pole. Drooping despite moist soil means root rot has started; act quickly.",
    },
    'fiddle-leaf-fig': {
        'light': "Bright indirect light is non-negotiable. Place within 60 cm of a large unobstructed window, ideally east-facing for gentle morning sun. Tolerates a few hours of direct morning sun once acclimated, but afternoon western sun burns the big leaves fast. The biggest mistake: putting it in a 'bright' interior corner that is actually 3 metres from any window. Use a light meter app: aim for 400 to 800 foot-candles. Rotate weekly so growth stays even, and never move it after it settles: the Fiddle hates change and drops leaves to protest.",
        'water': "Top 3 to 4 cm dry to the touch, then a deep soak until drainage. About 360 ml in a 25 cm pot in growing season, 240 ml in winter. Use the finger test, not the calendar. Brown spots from edges spreading inward mean underwatered or low humidity; brown spots from the centre with yellow halos mean root rot. Drooping new leaves recover within hours of a good drink; drooping plus crispy edges means you waited too long. Filtered or rainwater is ideal: Fiddles are sensitive to fluoride and chlorine in tap water (brown leaf tips are a telltale).",
        'food': "High-nitrogen feed (a 3-1-2 ratio like 24-8-16) monthly October to March. Essential for the big leaves: nitrogen-starved Fiddles produce pale, undersized new growth. Switch to a balanced fertiliser once or twice a year to avoid soil acidification. Top up with a layer of worm castings every 6 months for slow-release nutrition. Never feed a stressed plant (newly moved, recovering from leaf drop, or actively losing leaves): wait until you see a new leaf emerge before resuming.",
        'season': "Active growth October to March: expect 4 to 8 new leaves a year if conditions are right. Winter pause is significant: drop watering by 30 percent, stop fertilising, and accept that no new leaves will appear until spring. Wipe leaves monthly with a damp microfibre cloth (top and bottom). Dust is the silent killer: it blocks light and harbours spider mites. Repot every 18 to 24 months in spring, up one pot size only; Fiddles like being slightly root-bound and over-potting causes root rot fast. Use a well-draining indoor potting mix with 20 percent perlite added.",
        'trouble': "Sudden leaf drop after a move, draft, or temperature swing: Fiddles are drama queens about change. Put it back where it was if possible, otherwise wait 2 to 4 weeks; new leaves will eventually come. Brown spots from edges inward: underwatered or dry air; spots from centre with mushiness: root rot. Yellowing lower leaves: overwatered or hungry; check soil first. Pale washed-out new leaves: nitrogen deficiency. Spider mites and mealybugs are the main pests: wipe both sides of leaves weekly during pest season, treat with neem oil at first sign. Bacterial leaf spot (irregular brown patches with yellow halos that spread) needs immediate isolation and copper fungicide; trim affected leaves with sterilised scissors.",
    },
    'peace-lily': {
        'light': "Medium to low indirect light is ideal: north or east-facing windowsill or a metre or two inside a brighter room. Tolerates true low-light corners that would kill most houseplants, but flowers less and grows slowly. Direct sun even briefly burns the leaves to crispy yellow patches. Pale washed-out leaves mean too much light; deep dark green with no blooms means too little. The sweet spot for flowering is bright filtered light: behind a sheer curtain on an east-facing window is perfect. Rotate monthly.",
        'water': "When the top 2 cm is dry, or when leaves start a gentle droop (Peace Lily is dramatic about thirst: it will theatrically wilt, then bounce back within an hour of a deep drink). About 250 ml for a 20 cm pot, every 4 to 6 days in summer. Use room-temperature filtered water: brown leaf tips are usually a tap-water reaction to chlorine and fluoride. Empty the saucer; do not let it sit in water. Yellow leaves: overwatered or hard water buildup. Crispy brown tips: tap water sensitivity or low humidity. Flush the pot with plain water quarterly.",
        'food': "Half-strength balanced liquid feed every 6 weeks October to March. Peace Lilies are light feeders; over-fertilising causes brown leaf tips faster than under-fertilising. Stop feeding completely in winter. A pinch of magnesium sulphate (Epsom salt, quarter teaspoon dissolved in a litre) twice a year deepens leaf colour and supports flowering. If no blooms appear after 2 years of good care, try a higher-phosphorus bloom booster (10-30-20) twice in early spring.",
        'season': "Growth October to March; mostly dormant May to August. Flowers (those white spathes) appear opportunistically when light and humidity are right, typically spring through early summer but indoor specimens can bloom year-round. Cut spent flower stalks down to the base; they will not re-bloom. Repot every 2 to 3 years in spring; Peace Lilies actually like being slightly root-bound, which encourages flowering. Divide overgrown plants in spring: gently separate the root mass into 2 or 3 clumps, pot each up individually. Loves 50 to 70 percent humidity: a pebble tray or grouped plants help.",
        'trouble': "Drooping but not yellowing: thirsty, water now and watch the recovery. Yellow lower leaves: overwatered, ease back on watering and check drainage. Brown leaf tips: tap water (switch to filtered or rainwater) or low humidity. No flowers: not enough light, plant is too young (under 18 months), or it is overdue for a feed of phosphorus. Sticky leaves and small bumps: scale insects; scrape off with a fingernail or cotton bud dipped in rubbing alcohol. Spider mites in dry winter air: rinse in the shower monthly. Powdery white spots on leaves: powdery mildew from poor airflow; move to a more open spot. Toxic to cats and dogs if chewed: causes drooling and mouth irritation, rarely fatal but unpleasant.",
    },
    'snake-plant-laurentii': {
        'light': "Tolerant of almost anything from low light to direct sun, which is why Snake Plants thrive in offices and dim hallways. Best growth in bright indirect light: 1 to 2 metres from a window. In low light, growth slows to a crawl (one new leaf a year) but leaves stay healthy for years. Direct afternoon sun fades the yellow margins on Laurentii; morning sun is fine. The leaves are vertical for a reason: they evolved for high-altitude side-light, so a windowsill suits them better than a deep shelf.",
        'water': "Less is more. Wait until soil is bone-dry to the bottom of the pot before watering. In a 15 cm pot, about 180 ml every 3 to 4 weeks in summer, every 6 to 8 weeks in winter. Use the bottom-water method: set the pot in a tray of water for 20 minutes, then drain fully. Snake Plants store water in the leaves; overwatering causes the base to turn mushy and topple, which is fatal. Wrinkled or curled leaves mean genuinely underwatered (rare). Use a chunky cactus or succulent mix with extra perlite for drainage.",
        'food': "Cactus feed at half strength once every 6 to 8 weeks October to March. Snake Plants are extremely light feeders: too much fertiliser causes leaf-edge burn and leggy growth. Stop completely November to August. A teaspoon of worm castings on the soil surface once a year provides gentle slow-release nutrition. Avoid high-nitrogen feeds: they soften the leaves and reduce the upright structure.",
        'season': "Slow grower year-round but most active in warmer months. Repot only when the root mass cracks the pot (usually every 4 to 5 years): they prefer tight quarters. Best repotted in spring into a terracotta pot one size up. Propagation is easy: cut a healthy leaf into 10 cm sections, let the cut ends callous for a day, then stick base-down into damp soil; roots form in 4 to 6 weeks. Note: leaf cuttings of variegated Laurentii revert to plain green; for true Laurentii babies, divide the rhizome instead.",
        'trouble': "Mushy base, leaves toppling: severely overwatered or rotted at the rhizome. Unpot, cut off all mushy tissue with a sterile knife, dust cuts with cinnamon, let dry for a day, repot in fresh dry mix. Brown crispy tips: tap-water minerals or sun scorch (rare). Leaves leaning over despite firm base: too little light or the pot is too wide for the root mass. Pale yellow leaves: rare, usually means severe drought or root damage. Mealybugs in leaf crevices: dab with cotton bud dipped in rubbing alcohol. Snake Plants are toxic to pets if chewed: causes vomiting and drooling, rarely fatal.",
    },
    'zz-plant': {
        'light': "The ultimate low-light survivor: thrives in dim corners that would kill most houseplants. Best appearance in medium to bright indirect light: glossier leaves, faster growth. Avoid direct sun entirely (it burns the leaves to pale yellow patches that never recover). Tolerates fluorescent office lighting completely (it was the office plant of the 90s for good reason). If growth completely stalls for 6 months, light is probably the cause but it will not actually die in a dark corner.",
        'water': "When the soil is completely dry to the bottom of the pot. ZZ stores water in fat underground rhizomes the size of small potatoes; it would rather you forget than overwater. In a 20 cm pot, about 200 ml every 3 to 4 weeks in summer, every 6 to 8 weeks in winter. Use lukewarm water and bottom-water if you can: water on the rhizomes can cause rot. Yellow leaves: overwatered, the only common killer of ZZs. Wrinkled stems: thirsty but resilient. Drainage hole is essential.",
        'food': "Half-strength balanced feed every 6 to 8 weeks October to March only. ZZ Plants are notoriously slow and steady; over-feeding causes leggy weak growth and leaf burn. A handful of worm castings on the surface twice a year is often enough. Skip fertiliser entirely in winter.",
        'season': "Almost glacial growth: expect 1 to 3 new stems per year, each stem unfurling over 2 to 3 months. Most growth October to March in a warm room. Dormant in winter; no new growth and minimal water needs. Repot every 3 to 5 years in spring; the rhizomes will visibly fill the pot before it is time. Use a fast-draining mix (cactus mix with extra perlite). Propagation: divide the rhizomes in spring, or root single leaves in water (takes 6 to 12 months for a tiny rhizome to form, but it works).",
        'trouble': "Yellow leaves at the base: the most common complaint, almost always overwatered. Ease back and let the soil dry out fully. Yellow leaves spreading from the top: rare, usually severe overwatering with rotted rhizomes. Unpot, cut off any soft mushy rhizomes, repot in fresh dry mix and do not water for 2 weeks. Brown leaf tips: low humidity (rare problem) or tap water minerals. Mealybugs love ZZ stem nodes: spot-treat with rubbing alcohol on a cotton bud. Toxic to pets and people if chewed: contains calcium oxalate crystals that cause mouth irritation and stomach upset. Wash hands after pruning; the sap can irritate skin.",
    },
    'golden-pothos': {
        'light': "Adapts to almost any light from low to bright indirect. Best variegation (the gold splashes) in bright indirect light: a metre from an east-facing window is perfect. In low light, leaves stay green with little or no variegation and grow smaller; in too much direct sun, leaves bleach and crisp at the edges. If your Pothos is reverting to all green, move it brighter. Tolerant of fluorescent lighting in offices.",
        'water': "When the top 2 to 3 cm is dry. Pothos is a fast indicator: leaves wilt dramatically when thirsty and recover within 2 hours of a drink. About 200 ml in a 15 cm pot, every 7 to 10 days in summer, every 10 to 14 in winter. Overwatering causes yellow leaves and root rot quickly; underwatering is recoverable. Pothos is happy in pure water (no soil) for years: take a cutting at a node and pop it in a jar; roots form in days. Tap water is fine; not picky about water quality.",
        'food': "Balanced feed at half strength monthly October to March. Pothos is a moderate feeder: too much makes the variegation fade. Stop in winter. A pinch of slow-release pellets in spring lasts months. If leaves yellow and growth slows during the growing season, it is more likely overwatered than hungry.",
        'season': "Vigorous grower October to March; can extend 30 cm of vine per month if happy. Pinch tips weekly to keep bushy, or let it trail dramatically from a high shelf. Slows but never fully dormant: keep watering year-round, just less. Repot every 18 to 24 months in spring, up one pot size. Propagation is laughably easy: cut just below a node, root in water (1 to 2 weeks) or directly in soil. Cuttings from variegated plants will only stay variegated if the cutting has variegated leaves; all-green cuttings produce all-green plants.",
        'trouble': "Yellow leaves: overwatered, the most common issue. Black spots on leaves: bacterial leaf spot from leaves staying wet; water only the soil, not the foliage. Leggy with long bare stems and small leaves: too little light. Faded variegation: not enough light. Browning crispy tips: dry air or too much fertiliser. Mealybugs nest in the leaf-stem junctions: dab with alcohol on cotton bud. Pothos is toxic to cats and dogs if chewed: causes mouth irritation and drooling, rarely fatal but warrants a vet call.",
    },
    'pothos-marble-queen': {
        'light': "Bright indirect light is essential for keeping the dramatic white-and-green marbling. In low light, new leaves emerge mostly green and the plant slowly loses its signature look. Direct afternoon sun scorches the white sections, which have no chlorophyll to protect them. East-facing windowsill or 30 cm from a south-facing window (north in the southern hemisphere) is ideal. Variegation is light-driven: brighter equals whiter.",
        'water': "Top 3 cm dry, then a thorough soak. Marble Queen is slightly more sensitive than Golden Pothos because the white sections are slower to recover from stress. About 180 ml in a 15 cm pot in summer, less in winter. Yellow leaves: overwatered. Brown crispy patches on white sections: sun damage or fertiliser burn. Use room-temperature water; cold water can chill the leaves.",
        'food': "Half-strength balanced feed every 4 weeks October to March. Marble Queen is a slower grower than green Pothos (less chlorophyll, slower photosynthesis), so it needs less food. Stop in winter. Avoid high-nitrogen feeds: they encourage green reversion.",
        'season': "Growth October to March, slower than the all-green varieties due to reduced chlorophyll. Vines reach 1 to 2 metres indoors with patience. Pinch above a node with white-and-green variegation to encourage similar babies; cuttings from all-green leaves will only produce all-green offspring. Repot every 2 years in spring. Loves 50 percent humidity but tolerates household average.",
        'trouble': "All-green new leaves: light is too low, move brighter. Pure white leaves: pretty but doomed; they have no chlorophyll and will not last. Prune them off so the plant focuses on viable leaves. Brown patches on white sections: sun scorch or pest damage. Yellow lower leaves: overwatered. Mealybugs and spider mites: same treatment as Golden Pothos (alcohol swab, neem oil). Toxic to pets: same warnings as Golden.",
    },
    'spider-plant': {
        'light': "Bright indirect to medium light. Brightest light (without direct sun) produces the most plantlets (the baby 'spiders' on long stems). Tolerates lower light but stops producing offsets. Direct sun bleaches the white stripes. Hanging in a bright window or sat on a high shelf with indirect light is ideal. Outdoor in deep shade during summer is a treat; bring back in before the first cool nights.",
        'water': "When the top 2 cm is dry. About 150 ml in a 15 cm pot, every 5 to 7 days in summer, weekly in winter. Spider Plants store water in fleshy roots and tolerate occasional neglect. Use filtered or rainwater: famously sensitive to fluoride and chlorine, which cause brown leaf tips. Empty the saucer; soggy roots cause crown rot. The classic 'brown tips' problem is almost always tap water.",
        'food': "Half-strength balanced feed monthly October to March. Spider Plants are moderate feeders. Stop in winter. Over-feeding reduces plantlet production: the plant prioritises leaf growth over offsets. A pinch of slow-release pellets in spring is enough for most homes.",
        'season': "Active October to March; produces flower stalks and plantlets when day length and brightness peak. The little white flowers fade quickly but the plantlets are the show: leave them attached to keep the cascading look, or snip and pot up the rooted babies (just touch a plantlet to a small pot of soil while still attached; it will root in 2 to 3 weeks then you can cut the stolon). Repot every 18 months in spring; loves being slightly root-bound (encourages plantlet production).",
        'trouble': "Brown leaf tips: tap water minerals (especially fluoride). Switch to filtered or rainwater and trim the brown tips off at an angle. Yellow leaves: overwatered or hungry (check soil first). Pale washed-out leaves: too much direct sun. No plantlets after 18 months: needs brighter light, longer day length (a grow light helps), or it is too young (plantlets typically start at 2 years old). Aphids on flower stalks and new growth: blast with water or dab with insecticidal soap. Non-toxic to pets but cats love to chew the dangling leaves; they sometimes vomit from the irritation, not poisoning.",
    },
    'rubber-plant': {
        'light': "Bright indirect light brings out the deepest leaf colour (burgundy on Burgundy varieties, pink edges on Tineke). Tolerates lower light but variegated forms revert to plain green and growth slows. Direct morning sun is welcomed; afternoon sun bleaches dark varieties. Within a metre of a bright window is the sweet spot. Rotate weekly: Rubber Plants lean toward the light.",
        'water': "When the top 3 cm is dry. About 280 ml in a 20 cm pot in summer, 200 ml in winter. The thick waxy leaves store water; Rubber Plants tolerate brief drought better than overwatering. Yellow leaves dropping: overwatered. Curling leaves with crispy edges: thirsty or low humidity. Drooping with soft trunk: severe overwatering or root rot. The sap is white, sticky, and skin-irritant: wash any cuts immediately.",
        'food': "Balanced feed monthly October to March. Rubber Plants are moderate to heavy feeders during growing season; they push out big leaves. Switch to a high-potassium feed in late spring to encourage stem thickness. Stop in winter. A top-dressing of compost in early spring boosts overall vigour.",
        'season': "Active October to March; expect 6 to 12 new leaves a year if happy. Slows but does not fully dormant in winter. Wipe leaves with a damp cloth monthly: they collect dust like nothing else and look dramatically better clean. Repot every 2 to 3 years in spring; Rubber Plants tolerate being slightly root-bound. Use a well-draining mix with added perlite. Pruning encourages branching: cut just above a leaf node in spring; the plant releases sticky white sap, which is normal.",
        'trouble': "Lower leaves yellowing and dropping: usually overwatered or the plant has been moved (drafts and temperature swings cause leaf drop). Brown leaf edges: dry air or fertiliser salt buildup; flush the pot quarterly. Loss of variegation on Tineke or Ruby: not enough light. Sticky sap drips: normal latex; on Variegated Tineke, white sap can drip from leaf scars after pruning. Scale insects on stems: scrape with thumbnail or dab with alcohol. Spider mites in winter: rinse leaves in the shower monthly. Toxic to pets if chewed: causes mouth irritation and stomach upset. The sap can cause skin rashes in sensitive people.",
    },
    'boston-fern': {
        'light': "Bright indirect light. No direct sun: fronds yellow and crisp within hours. North-facing window or a metre or two from an east or west-facing window is ideal. In low light fronds yellow and drop from the bottom up. In a bathroom with frosted glass and good light, Boston Ferns are particularly happy because of the humidity.",
        'water': "Keep evenly moist, never soggy and never bone-dry. About 280 ml in a 20 cm pot every 3 days in summer, every 5 to 7 days in winter. The classic Boston Fern problem is letting it dry out: fronds turn brown and crispy from the tips and the plant can drop most of its foliage in a single dry weekend. Use room-temperature filtered water; tap water minerals cause browning. Bottom-watering once a fortnight keeps the root ball evenly moist.",
        'food': "Half-strength balanced liquid feed every 3 to 4 weeks October to March. Boston Ferns are surprisingly heavy feeders during growing season but burn easily; halve manufacturer's strength. A pinch of fish emulsion in spring (smelly but effective) boosts frond density. Skip fertiliser November to August.",
        'season': "Active October to March, slows in cooler months but does not go fully dormant. Loves 60 to 80 percent humidity: a pebble tray, daily misting, or grouping with other plants helps. Bathroom or kitchen placement keeps them happiest. Repot every 18 to 24 months in spring; divide the root ball into 2 or 3 clumps and pot each up. Keep away from heating vents and air conditioners; dry moving air kills them faster than under-watering.",
        'trouble': "Fronds turning brown and crispy from the tips: low humidity or dried out. Catch it early: a deep soak and a humid spell often saves it. Yellow fronds: overwatered or hungry. Fronds dropping from the base: normal seasonal renewal at low rates; if accelerating, check root health. Pale washed-out fronds: too much light or fertiliser burn. Spider mites and scale love stressed ferns: rinse fronds in the shower monthly, treat with insecticidal soap. The white tufts on the underside of fronds are normal sori (spore patches), not pests. Non-toxic to pets.",
    },
    'philodendron-heartleaf': {
        'light': "Bright indirect to medium light. Tolerates surprisingly low light (one of the most shade-tolerant trailing plants) but variegated cultivars need brighter light to keep their markings. Direct afternoon sun burns the heart-shaped leaves. East-facing windowsill or 1 to 2 metres from a south-facing window is ideal. Long vines lean toward light: rotate the pot monthly.",
        'water': "When the top 2 to 3 cm is dry. About 180 ml in a 15 cm pot, every 7 to 10 days in summer, every 10 to 14 in winter. Philodendrons are forgiving: a missed week is fine, but soggy roots are fatal. Yellow leaves: overwatered. Crispy edges: dry air or thirst. Heart-shaped leaves perk up dramatically after a deep drink. Bottom-water if possible to encourage strong roots.",
        'food': "Half-strength balanced feed monthly October to March. Philodendron Heartleaf is a moderate feeder; over-fertilising causes long bare stems with small leaves. Stop in winter. A pinch of slow-release pellets in spring lasts the season for a hanging basket.",
        'season': "Active October to March; vines extend 15 to 30 cm per month if happy. Pinch tips weekly to keep bushy: each cut sends out 2 new growth points. Cuttings root in water in days: snip below a node, pop the cutting in a jar of water, plant in soil when roots are 5 cm long. Repot every 2 years in spring; tolerates being root-bound which actually encourages denser foliage. Heart-shaped leaves get bigger with age and a moss pole.",
        'trouble': "Yellow lower leaves: overwatered, the usual cause. Black spots: bacterial leaf spot from wet foliage; water the soil not the leaves. Leggy with long bare stems: not enough light or hungry; move brighter and pinch tips. Pale washed-out leaves: too much sun. Mealybugs in leaf joints: alcohol swab. Spider mites in dry air: rinse monthly. Toxic to cats and dogs if chewed: causes mouth irritation and drooling. Mildly irritating sap on skin in sensitive people.",
    },
    'pilea-peperomioides': {
        'light': "Bright indirect light is essential. East or north-facing window is perfect (south or west in southern hemisphere). Pilea grows toward light: leaves tilt and the stem leans. Without a quarter turn every watering, the plant becomes lopsided within weeks. Some direct morning sun is fine but afternoon sun bleaches the coin-shaped leaves. Pups (baby plants) appear faster in good light.",
        'water': "When the top 2 cm is dry. About 150 ml in a 15 cm pot, every 5 to 7 days in summer, every 10 in winter. Pilea is dramatic about thirst: leaves droop and curl, then bounce back within an hour of a drink. Overwatering causes yellow leaves and stem rot. Use room-temperature water; bottom-water if you can. Drainage holes are essential.",
        'food': "Half-strength balanced feed every 4 weeks October to March. Pilea is a moderate feeder. Stop in winter. A pinch of slow-release pellets in spring is gentle and lasts. Over-feeding causes leggy stems and pale leaves.",
        'season': "Active October to March, with peak growth in spring. Produces baby pups around the base year-round if happy: a clear sign of health. Pot pups up when they have 3 to 4 leaves and a small root system; gently dig them out from the mother's pot. Repot every 18 months in spring. Use a well-draining mix with extra perlite. Tolerates 40 to 60 percent humidity (household average is fine).",
        'trouble': "Yellow lower leaves: overwatered. Curling leaves: too much sun or thirst. Drooping coin-leaves: thirsty, water now. Pale new growth: hungry, feed. Leggy with long bare stem: too little light; the bottom leaves will not regrow but the new growth at the top will be denser if you move it brighter. Brown spots on leaves: cold draft or watering with cold water. Aphids on new growth: blast with water. Non-toxic to pets, one of the safer options.",
    },
    'bird-of-paradise': {
        'light': "Direct sun, the more the better. Needs 4 to 6 hours of bright direct light daily to flower indoors (and even then, indoor blooms are rare and take 5+ years to first appear). South or west-facing window at minimum. Tolerates bright indirect light but stays vegetative forever. The big paddle-shaped leaves split naturally in wind; in still indoor air they stay intact, which is normal not a problem. Outdoor summer holiday in dappled shade is welcomed.",
        'water': "When the top 3 to 4 cm is dry. About 400 ml in a 25 cm pot every 5 to 7 days in summer, every 10 to 14 in winter. Bird of Paradise is thirsty but hates wet feet: deep soak, then full dry-out. Yellow leaves: overwatered. Brown crispy edges: dry air or sun-stressed (despite needing sun). Filtered or rainwater is best: brown leaf tips often signal tap-water sensitivity. Drainage hole is essential.",
        'food': "Heavy feeder during growing season: balanced liquid feed every 2 weeks October to March. Switch to a high-phosphorus bloom booster (10-30-20) in mid-spring if you are hoping for flowers. Stop entirely in winter. A top-dressing of compost twice a year supports the big leaves.",
        'season': "Strong growth October to March, slows in winter. Each new leaf takes 4 to 6 weeks to unfurl. Splits in mature leaves are normal: they evolved for windy savannas. Repot every 2 to 3 years in spring; Bird of Paradise actually likes being slightly root-bound (encourages flowering). Divide overgrown clumps in spring: separate the rhizomes with a sharp knife, dust cuts with cinnamon, pot up. Indoor flowering requires patience: bright direct light for years and a slightly stressed root system.",
        'trouble': "Curling leaves: thirsty or underwatered, or paradoxically too much sun without enough water. Brown edges: low humidity or salt buildup; flush the pot quarterly. Yellow lower leaves: overwatered or hungry. No flowers after 5 years: not enough light. Spider mites on leaf undersides: rinse monthly. Scale on stems: scrape off and treat with neem. Toxic to pets if chewed: causes mouth irritation, drooling, mild stomach upset. The seeds are more toxic but rarely accessed.",
    },
    'money-tree': {
        'light': "Bright indirect light is ideal. Tolerates medium light (about 1.5 metres from a window) but grows slowly. Direct sun for more than an hour bleaches the palmate leaves. East-facing windowsill is perfect. Rotate weekly: Money Trees lean dramatically toward light. Braided trunks were trained as saplings; new growth at the top will not braid itself.",
        'water': "When the top 3 cm is dry. About 260 ml in a 20 cm pot every 7 to 10 days in summer, every 14 in winter. Money Trees prefer a deep soak with full dry-out between, even though they are tropical. Yellow leaves dropping: overwatered. Wrinkled trunk: underwatered (rare but recoverable with a long deep drink). Despite the name, Pachira aquatica grows in seasonally flooded forests, so it tolerates occasional soggy soil better than most, but indoor pots rarely drain fast enough.",
        'food': "Balanced feed at half strength monthly October to March. Money Trees are moderate feeders. Stop in winter. A pinch of slow-release pellets in spring is sufficient for most plants.",
        'season': "Active October to March, slows but stays evergreen in winter. Leaf drop in winter is normal at low rates; if accelerating, check for cold drafts (Money Trees hate temperatures below 13C). Repot every 2 to 3 years in spring; the braided trunks need a wider pot than the small root ball suggests. Wipe leaves monthly. Pruning to control size: cut just above a leaf node; the plant branches readily.",
        'trouble': "Yellow leaves: overwatered, the most common issue by far. Brown crispy edges: dry air or salt buildup. Sticky leaves with small bumps: scale insects; scrape and treat with neem. Spider mites in winter: rinse monthly. Sudden leaf drop after a move: stress response, will recover. Trunk going soft: stem rot from overwatering, often fatal once it spreads; cut healthy growth above the rot and try to re-root in water. Non-toxic to pets and people: one of the safer options for cat homes.",
    },
    'chinese-evergreen': {
        'light': "Low to medium indirect light. One of the most shade-tolerant houseplants: thrives in dim hallways and north-facing rooms. Variegated cultivars (silver-marked Maria, pink-flushed Siam Aurora) need brighter indirect light to keep their colours. Direct sun fades leaf patterns within days. East-facing windowsill is the sweet spot for variegated forms.",
        'water': "When the top 2 to 3 cm is dry. About 220 ml in a 18 cm pot every 7 to 10 days in summer, every 14 in winter. Aglaonema is forgiving: tolerates occasional under-watering and is harder to kill by underwatering than overwatering. Yellow lower leaves: overwatered. Curling leaves: dry air or thirst. Filtered water is best; tap water tip-burn is a chronic complaint.",
        'food': "Half-strength balanced feed every 6 to 8 weeks October to March. Aglaonema is a light feeder; over-fertilising causes leaf-edge burn and pale washed-out colour. Stop in winter. A pinch of slow-release pellets in spring is gentle and effective.",
        'season': "Slow steady grower year-round, with peak activity October to March. Produces small white spathes (similar to Peace Lily flowers) opportunistically; not the main draw. Repot every 2 to 3 years in spring; Aglaonema likes a snug pot. Propagation by stem cuttings in water: snip a 10 to 15 cm length with at least 2 nodes, root in water in 3 to 4 weeks, plant in soil. Loves 50 percent humidity but tolerates dry indoor air.",
        'trouble': "Yellow lower leaves: overwatered. Brown crispy edges: tap water minerals or low humidity. Faded variegation: too little light, move brighter. Pale washed-out new growth: too much sun or hungry. Mealybugs in leaf joints: alcohol swab. Spider mites in winter: rinse monthly. Toxic to cats and dogs if chewed: causes mouth irritation, drooling, swelling. The sap can cause skin rashes; wear gloves when pruning.",
    },
    'dracaena-marginata': {
        'light': "Bright indirect light is ideal. Tolerates medium light (1.5 metres from a window) but red leaf edges fade. Direct afternoon sun bleaches and scorches. North or east-facing window is perfect. The dragon tree leans toward light: rotate weekly. Tolerant of office fluorescent lighting.",
        'water': "When the top 3 cm is dry; bone-dry between waterings is preferred. About 240 ml in a 20 cm pot every 10 to 14 days in summer, every 3 to 4 weeks in winter. Drought-tolerant: stores water in the cane-like trunk. Yellow leaves: overwatered, the main killer. Brown crispy tips: tap water fluoride sensitivity (a chronic Marginata complaint). Use rainwater or filtered water if you can; trim brown tips off at an angle for a clean look.",
        'food': "Half-strength balanced feed every 6 to 8 weeks October to March. Dracaena Marginata is a light feeder. Stop in winter. Too much fertiliser causes leaf-edge burn.",
        'season': "Slow steady grower year-round, more active October to March. The bottom leaves naturally yellow and drop as the cane grows taller; that is normal not a problem. Repot every 3 to 4 years in spring; tolerates being root-bound. Use a well-draining mix. Propagation: cut a healthy cane section, dip in rooting hormone, stick in moist perlite; roots in 4 to 8 weeks. The mother plant will sprout new growth from the cut point.",
        'trouble': "Brown leaf tips: fluoride in tap water, the most common issue. Switch to filtered or rainwater. Yellow leaves: overwatered. Drooping leaves: severe drought (rare) or root rot (more common). Faded red edges: too little light. Bottom leaves falling: normal cane growth, not a problem unless rapid. Mealybugs in leaf crevices: alcohol swab. Spider mites: rinse monthly. Toxic to cats and dogs (severe in cats): causes vomiting, drooling, loss of appetite, dilated pupils. One of the most reported plant poisonings to vets.",
    },
    'calathea-orbifolia': {
        'light': "Medium indirect light only. No direct sun, ever: even brief direct exposure bleaches the silver-and-green stripes. North-facing window or a metre into a brighter room. In low light, leaves curl up and growth stops; in too much light, patterns fade and edges crisp. Calatheas evolved on the rainforest floor: dappled light is what they want.",
        'water': "Keep evenly moist but never soggy. About 200 ml in a 18 cm pot every 4 to 5 days in summer, every 7 to 10 in winter. Calathea Orbifolia is famously fussy about water: distilled, rainwater, or filtered only. Tap water minerals cause brown edges within weeks. Bottom-watering helps avoid splashing the velvety leaves. Drooping leaves bounce back overnight after a drink; permanent droop means root issues.",
        'food': "Quarter-strength balanced feed every 3 to 4 weeks October to March. Orbifolia is sensitive to fertiliser salts; halve every recommendation and flush the pot monthly. Stop in winter. Worm castings or fish emulsion in spring are gentler than synthetic feeds.",
        'season': "Active October to March, slows in cooler months. Loves 60 to 80 percent humidity: a pebble tray, daily misting, or a humidifier is often necessary. Bathroom placement works well. Leaves move noticeably: closed up at night, opened during the day (the prayer-plant family behaviour). Repot every 18 months in spring; divide the root mass into clumps if it has grown wide. Use a peat-based mix with extra perlite.",
        'trouble': "Brown crispy edges: tap water minerals or low humidity, the universal Calathea complaint. Yellow leaves: overwatered. Curling leaves: thirsty or too much light. Spider mites are the number-one pest: tiny webs on leaf undersides, rinse monthly and treat with neem oil. Faded patterns: too much light. Leaves not opening fully: stressed (recent move, draft, or cold). Non-toxic to pets, a major selling point.",
    },
    'calathea-rattlesnake': {
        'light': "Medium indirect light. No direct sun. North or east-facing window is ideal. The wavy patterned leaves fade in too much light. Rattlesnake is slightly more forgiving than Orbifolia but still picky.",
        'water': "Evenly moist, never soggy. About 180 ml in a 15 cm pot every 4 to 5 days in summer. Filtered or rainwater is essential: tap water tip-burn is severe. Bottom-water if possible. Drooping leaves perk up within hours of a drink. Yellow leaves: overwatered. Brown crispy edges: hard water or low humidity.",
        'food': "Quarter to half-strength balanced feed every 4 weeks October to March. Sensitive to fertiliser salts: flush the pot monthly during the feeding season. Stop in winter.",
        'season': "Active October to March; produces purple-undersided wavy leaves rapidly when happy. Closes up at night dramatically (the rattlesnake nickname). Loves 60 to 70 percent humidity. Repot annually in spring; divide if it has formed clumps. Use a peat-based mix with perlite for drainage.",
        'trouble': "Brown crispy edges: tap water, the chronic Calathea problem. Yellow leaves: overwatered. Curling: thirsty or too cold (under 16C). Spider mites: rinse monthly. Faded patterns: too much light or hungry. Non-toxic to pets.",
    },
    'parlor-palm': {
        'light': "Low to medium indirect light. One of the few palms that thrives in genuinely dim corners. North-facing window or interior shelf is fine. Direct sun bleaches fronds; even bright indirect can be too much in summer. The Victorians grew these in dimly-lit parlours for a reason.",
        'water': "When the top 2 to 3 cm is dry. About 220 ml in a 18 cm pot every 7 to 10 days in summer, every 14 in winter. Parlor Palms are surprisingly sensitive to overwatering despite tropical origins. Yellow fronds: overwatered. Crispy brown tips: tap water minerals or low humidity. Filtered or rainwater is gentler.",
        'food': "Half-strength balanced feed every 6 weeks October to March. Light feeder; too much fertiliser causes leaf-edge burn. Stop in winter.",
        'season': "Slow steady grower year-round, with new fronds appearing irregularly. Loves 50 to 60 percent humidity but tolerates household average. Wipe fronds monthly: they catch dust like nothing else. Repot every 3 to 4 years in spring; do not divide (Parlor Palms hate root disturbance). Use a well-draining palm mix.",
        'trouble': "Brown frond tips: tap water or low humidity. Yellow fronds: overwatered. Spider mites are the main pest: silvery flecks on fronds, fine webs on undersides. Rinse fronds in the shower monthly, treat with neem at first sign. Mealybugs in frond junctions: alcohol swab. Faded green: too much light. Non-toxic to pets and people.",
    },
    'kentia-palm': {
        'light': "Medium indirect light. Tolerates lower light than most palms. East or north-facing window, or 2 metres from a south-facing one. Direct afternoon sun bleaches and crisps fronds. Tolerant of moves and reasonable indoor variability.",
        'water': "When the top 3 cm is dry. About 320 ml in a 25 cm pot every 10 days in summer, every 14 to 21 in winter. Kentia is slow and steady about everything including water uptake. Overwatering causes yellow fronds and root rot; underwatering causes brown crispy tips. Filtered water is gentler on the tips. Flush the pot quarterly to wash out salt buildup.",
        'food': "Balanced feed at half strength monthly October to March. Light feeder, sensitive to fertiliser salts: flush quarterly. Stop in winter.",
        'season': "Famously slow grower: 1 to 2 new fronds per year. That is normal; Kentias are not for the impatient. Most growth October to March. Wipe fronds monthly. Repot every 4 to 5 years only; Kentias hate root disturbance more than most palms. Use a well-draining palm mix in a deep pot (the roots grow down, not wide).",
        'trouble': "Brown frond tips: mineral buildup from tap water; flush with rainwater quarterly. Yellow fronds: overwatered. Pale washed-out fronds: magnesium deficiency; a pinch of Epsom salt twice a year helps. Spider mites: rinse monthly. Scale insects on frond stems: scrape and treat. Non-toxic to pets. Kentias are the most expensive palm partly because they grow so slowly; treat them well and they live 20+ years indoors.",
    },
    'areca-palm': {
        'light': "Bright indirect light, lots of it. The most light-hungry common indoor palm. East-facing window for morning sun, or near a bright south-facing window with a sheer curtain. In low light, Arecas yellow rapidly. Direct afternoon sun scorches.",
        'water': "Keep evenly moist; do not let the soil dry out completely. About 360 ml in a 25 cm pot every 4 to 5 days in summer, every 7 to 10 in winter. Areca is thirstier than most palms because of its high transpiration rate (large frond surface area). Yellow fronds: overwatered if mushy at base, underwatered if crispy. Use filtered or rainwater; Areca is sensitive to fluoride and chlorine.",
        'food': "High-nitrogen palm-specific feed monthly October to March. Areca is a heavy feeder during growing season; magnesium and potassium are particularly important. Pale washed-out fronds usually mean magnesium deficiency: a pinch of Epsom salt dissolved in water twice a year helps. Stop fertilising in winter.",
        'season': "Active October to March; can push 6 to 10 new fronds a year if happy. Loves 60 to 70 percent humidity; dry indoor winter air causes brown tips. Repot every 2 to 3 years in spring; divide overgrown clumps into 2 or 3 sections. Use a palm mix with extra perlite.",
        'trouble': "Brown frond tips: low humidity, the most common complaint. Yellow fronds: overwatered or magnesium deficient. Spider mites are the biggest pest by far: silvery flecks on fronds, fine webs underneath. Rinse fronds in the shower fortnightly during pest season, treat with neem oil. Pale washed-out new growth: magnesium or iron deficiency. Non-toxic to pets, often recommended for homes with cats and dogs.",
    },
    'anthurium-andraeanum': {
        'light': "Bright indirect light. East-facing windowsill is perfect, or 1 metre from a south-facing window with a sheer curtain. More light equals more flowers; in dim corners Anthuriums produce only foliage. Direct afternoon sun bleaches the waxy red spathes. Rotate weekly for even growth.",
        'water': "When the top 2 to 3 cm is dry. About 200 ml in a 15 cm pot every 5 to 7 days in summer, every 10 in winter. Anthuriums hate wet feet but also hate true drought. Yellow leaves: overwatered. Drooping leaves with crispy edges: thirsty. Use room-temperature water; cold water shocks the tropical roots. A chunky aroid mix (orchid bark, perlite, coir) drains best; regular potting soil suffocates the roots.",
        'food': "High-phosphorus bloom booster (10-30-20) every 3 weeks October to March to encourage spathes. Anthuriums are moderate feeders that prioritise phosphorus over nitrogen during flowering. Stop in winter. Worm castings as a top-dressing in spring give gentle slow-release nutrition.",
        'season': "Flowers nearly year-round in the right conditions: each spathe lasts 6 to 8 weeks before fading. Cut spent spathes at the base. Most growth October to March. Repot every 18 to 24 months in spring into a chunky aroid mix. Divide overgrown clumps. Loves 60 to 70 percent humidity; a pebble tray helps.",
        'trouble': "No flowers: not enough light or wrong fertiliser ratio. Move brighter and switch to a bloom booster. Brown spathe edges: low humidity or hard water. Yellow leaves: overwatered. Drooping despite moist soil: root rot has started; unpot, trim mushy roots, repot in fresh chunky mix. Mealybugs and scale: alcohol swab and neem. Spider mites on leaf undersides: rinse fortnightly. Toxic to pets and people if chewed: contains calcium oxalate crystals that cause mouth irritation, drooling, swelling. Sap can cause skin rashes; wear gloves when pruning.",
    },
    'croton': {
        'light': "Bright direct light for the dramatic colours: yellows, oranges, reds, purples all need 4 to 6 hours of sun to develop. East or south-facing window is ideal. In low light, new leaves emerge plain green and the plant slowly loses its colour palette. Direct afternoon sun in summer can scorch; a sheer curtain helps. Rotate weekly.",
        'water': "When the top 2 to 3 cm is dry. About 260 ml in a 20 cm pot every 5 to 7 days in summer, every 10 in winter. Croton is thirsty during growing season but cannot tolerate soggy roots. Famous for dramatic leaf drop in response to: under-watering, over-watering, drafts, temperature changes, being moved. The trick is consistency. Use room-temperature water.",
        'food': "Balanced feed monthly October to March. Croton is a moderate feeder; over-feeding causes leaf-edge burn and pale colours. A pinch of magnesium twice a year supports leaf colour.",
        'season': "Active October to March, slows in cooler months. Hates temperatures below 16C: a cold draft will trigger total leaf drop overnight. Repot every 2 years in spring. Wipe leaves monthly to keep them glossy and to spot pests early. New growth at the top is normal: the bottom leaves naturally drop as the plant matures, leaving a bare stem if not pruned. Prune in spring to encourage branching.",
        'trouble': "Massive leaf drop: cold draft, sudden move, or watering inconsistency. Recovers if conditions stabilise (can take 2 to 3 months to regrow). Faded colours: too little light. Brown crispy edges: dry air or under-watering. Yellow lower leaves: overwatered. Spider mites and mealybugs love stressed Crotons: rinse fortnightly during pest season. Toxic to pets if chewed: causes mouth irritation, drooling, vomiting. The milky sap is skin-irritant and can stain.",
    },
    'schefflera': {
        'light': "Bright indirect light. Tolerates medium light at the cost of leggy growth and smaller leaves. Variegated cultivars need the brightest indirect light to keep their cream-and-green pattern. Direct afternoon sun scorches; gentle morning sun is fine. Rotate weekly: Scheffleras lean toward light.",
        'water': "When the top 3 cm is dry. About 280 ml in a 20 cm pot every 7 to 10 days in summer, every 14 in winter. Schefflera is moderately drought-tolerant: it would rather you forget than overwater. Yellow lower leaves dropping: overwatered, the main complaint. Wrinkled stems: thirsty (rare).",
        'food': "Balanced feed at half strength monthly October to March. Moderate feeder. Stop in winter. A pinch of slow-release pellets in spring lasts months.",
        'season': "Active October to March; slows but stays evergreen in winter. Pruning encourages branching: cut just above a leaf node. Without pruning, Scheffleras tend to grow tall and leggy. Repot every 2 to 3 years in spring. Wipe leaves monthly. Propagation by stem cuttings: 15 cm cuttings with at least 3 nodes, root in water or moist soil; can take 6 to 8 weeks.",
        'trouble': "Lower leaves yellowing and dropping: overwatered, the most common issue. Brown leaf tips: low humidity or salt buildup; flush quarterly. Leggy with small new leaves: not enough light or hungry. Faded variegation: light too low. Spider mites and scale: rinse monthly, treat with neem oil. Toxic to cats and dogs if chewed: causes mouth irritation, drooling, vomiting. Sap can cause skin rashes.",
    },
    'yucca': {
        'light': "Direct sun, as much as possible. Yucca thrives in the brightest spot in your home: south or west-facing window. Tolerates medium indirect light but grows slowly and may not stay upright. Outdoor summer holiday in full sun is welcomed. Variegated cultivars need bright light to keep their markings.",
        'water': "When the soil is bone-dry to the bottom of the pot. About 280 ml in a 25 cm pot every 14 to 21 days in summer, every 4 to 6 weeks in winter. Yucca is drought-adapted: stores water in the trunk and roots. Overwatering is the number-one killer by a wide margin. Yellow leaves: overwatered. Wrinkled leaves: thirsty (rare).",
        'food': "Cactus feed at full strength monthly October to March. Yucca is a moderate feeder during growing season. Stop in winter. Too much nitrogen makes the leaves floppy.",
        'season': "Slow steady grower, more active October to March. Bottom leaves naturally yellow and drop as the trunk grows: that is normal. Repot every 4 to 5 years in spring; Yucca prefers a tight pot. Use a fast-draining cactus mix in a heavy pot (Yuccas are top-heavy). Propagation: cut a healthy trunk section, let the cut callous for a week, root in dry sand; roots in 6 to 10 weeks.",
        'trouble': "Yellow leaves at the base: overwatered, the only common killer. Mushy trunk: severe root rot; cut healthy growth above and try to re-root. Brown crispy tips: low humidity (rare) or salt buildup. Pale green: not enough light. Scale insects on the trunk: scrape and treat. Toxic to dogs and cats if chewed: causes vomiting, drooling, lethargy. The sharp leaf tips can cause physical injury (eye scratches especially); be careful around children and pets.",
    },
    'sago-palm': {
        'light': "Bright direct sun, ideally 4 to 6 hours a day. Tolerates medium indirect light but grows even more slowly (and Sagos are already glacial). South or west-facing window is ideal. Direct afternoon sun is welcomed, unlike most houseplants.",
        'water': "When the top 3 to 4 cm is dry. About 280 ml in a 25 cm pot every 10 to 14 days in summer, every 3 to 4 weeks in winter. Sago is drought-tolerant; stores water in the woody trunk and roots. Hates wet feet: drainage is essential. Yellow fronds: overwatered, the main killer.",
        'food': "Balanced feed monthly October to March. Sago is a light feeder. A magnesium supplement (Epsom salt, quarter teaspoon dissolved in a litre of water) twice a year supports frond colour. Stop fertilising in winter.",
        'season': "Famously slow: one flush of new fronds per year, usually in late spring. The new fronds emerge soft and vulnerable; do not touch or move the plant while they are forming or they will deform permanently. Once they harden off (4 to 6 weeks) they are tough. Repot every 4 to 5 years only; Sagos hate disturbance. Use a fast-draining mix in a deep pot.",
        'trouble': "Yellow fronds: overwatered or magnesium-deficient. Brown new fronds: touched or moved during emergence; cannot be fixed for that flush. Slow or no new growth: normal Sago pace, not a problem unless several years pass. Mealybugs and scale on the trunk: scrape and treat with neem. Severely toxic to pets, particularly dogs: one seed can be fatal, the rest of the plant is highly toxic (causes liver failure). Keep well out of reach of dogs that chew. The toxin (cycasin) has no antidote; immediate vet care is essential if ingested.",
    },
    'jade-plant': {
        'light': "Direct sun, ideally 4 to 6 hours a day. South or west-facing window is essential for the compact tree-like growth and red-edged leaves. In low light, Jade stretches into leggy weak growth with smaller pale leaves. Outdoor summer in full sun is welcomed; bring back indoors before the first cool nights.",
        'water': "When the soil is bone-dry to the bottom of the pot. About 200 ml in a 20 cm pot every 2 to 3 weeks in summer, every 4 to 6 weeks in winter. Jade is drought-adapted; stores water in the fleshy leaves. Overwatering causes leaf drop and root rot quickly. Wrinkled leaves: thirsty, water now. Mushy leaves: overwatered, ease back immediately.",
        'food': "Cactus feed at half strength every 6 to 8 weeks October to March. Jade is a light feeder. Stop in winter completely. Over-feeding causes leggy weak growth.",
        'season': "Slow steady grower year-round; most active October to March. Mature Jades (5+ years) can produce small star-shaped white or pink flowers in late autumn if given a cold dry rest in late winter. Propagation is famously easy: snap off a leaf or stem cutting, let it callous for a few days, lay on dry soil; roots form in 2 to 3 weeks. Repot every 3 to 4 years; Jade likes being slightly root-bound.",
        'trouble': "Leaf drop in mass: overwatered. Wrinkled leaves: thirsty (rare). Leggy stretched growth: not enough light, the most common appearance issue. Move brighter and prune leggy stems back; new growth will be more compact. Mealybugs in leaf joints: alcohol swab. Mildly toxic to pets if chewed: causes vomiting, depression, slowed heart rate in dogs. Not life-threatening but warrants a vet call.",
    },
    'aloe-vera': {
        'light': "Direct sun, 4 to 6 hours daily. South or west-facing windowsill is ideal. Aloe leaves develop their best green-grey colour and stay compact in bright light; in low light they stretch out floppy and pale. Outdoor summer in full sun is welcomed once acclimated (introduce gradually to avoid sunburn).",
        'water': "When the soil is bone-dry to the bottom of the pot. About 200 ml in a 18 cm pot every 2 to 3 weeks in summer, every 4 to 6 weeks in winter. Aloe stores water in the fleshy leaves and roots; overwatering is the main killer. Yellow mushy leaves: overwatered. Wrinkled curled leaves: thirsty (rare). Use a cactus mix with extra perlite; standard potting soil holds too much water.",
        'food': "Cactus feed at half strength every 8 to 10 weeks October to March. Aloe is a very light feeder. Stop in winter. Over-feeding causes leaf-edge burn and pale colour.",
        'season': "Active October to March, dormant in cooler months. Produces baby pups (offsets) around the base when happy: gently separate and pot up when they have their own roots (usually 8 to 10 cm tall). Mature plants (3+ years) may produce tall flower spikes in winter to spring, with tubular orange or yellow blooms. Repot every 2 to 3 years in spring. Use a heavy pot: Aloes are top-heavy.",
        'trouble': "Yellow mushy leaves: overwatered, the most common death. Cut off all mushy tissue, dust cuts with cinnamon, let dry for a few days, repot in fresh dry mix. Brown crispy tips: salt buildup or sun scorch (rare). Leggy stretched growth: not enough light. Flat or curling leaves: thirsty (water once). The gel inside leaves is famously soothing on minor burns and sunburn (break off an outer leaf, slice lengthwise, apply gel directly). Mildly toxic to pets if eaten in quantity: causes vomiting and diarrhoea.",
    },
    'string-of-pearls': {
        'light': "Bright indirect light with some direct morning sun. The pearls develop their best plump round shape in bright light; in low light they become elongated and the strings turn leggy. Direct afternoon sun shrivels the pearls. East-facing window is perfect; hanging in a south-facing window with a sheer curtain works too.",
        'water': "Bone-dry between waterings. About 100 ml every 2 to 3 weeks in summer, every 4 to 6 weeks in winter. String of Pearls is drought-tolerant; stores water in the pearls. Overwatering causes pearls to burst and rot at the base. Shrivelled pearls: thirsty, water now. Mushy pearls or stems: overwatered, lethal if not caught quickly. Use a cactus mix; standard soil holds too much water.",
        'food': "Cactus feed at half strength every 8 weeks October to March only. Very light feeder. Stop completely in winter. Over-feeding causes weak elongated pearls.",
        'season': "Active October to March; produces fluffy white cinnamon-scented flowers in late autumn if happy (an underrated charm). Stems can extend 30 cm or more per growing season. Propagation is laughably easy: lay any string section on damp soil, it roots from the nodes within 2 to 3 weeks. To rejuvenate a leggy hanging basket, lay the long strings on the surface of the soil; they root in place and double the density. Repot every 2 to 3 years in spring.",
        'trouble': "Shrivelled pearls: thirsty. Burst or mushy pearls: overwatered. Brown crispy strings: sun scorch (rare) or severe drought. Mealybugs nest along the strings: dab with alcohol on a cotton bud. Spider mites in dry winter air: rinse fortnightly. Pearls drop off at the slightest touch: the plant is stressed (recent move, cold, or dry); stabilise conditions. Toxic to pets if chewed: causes vomiting, diarrhoea, lethargy. The sap can cause skin rashes.",
    },
    'african-violet': {
        'light': "Bright indirect light, no direct sun. East or north-facing windowsill is perfect. In low light, no flowers and pale floppy leaves; in too much light, scorched yellow patches and faded blooms. A fluorescent grow light 30 cm above the plant for 12 hours a day is the classic African Violet setup and produces near-continuous flowering. Rotate the pot weekly.",
        'water': "When the top 1 to 2 cm is dry. About 100 ml in a 12 cm pot every 5 to 7 days in summer, every 10 in winter. Critical: never get water on the fuzzy leaves; the cold water causes pale ring spots that never fade. Bottom-water: set the pot in a saucer of room-temperature water for 20 minutes, then drain. Use room-temperature filtered or rainwater. Yellow leaves: overwatered or hard water.",
        'food': "African Violet specific feed (high-phosphorus, like 7-9-5) at quarter strength every watering during growing season (October to March). The 'every watering, weak feed' approach produces best flowering. Stop in winter. Flush the pot with plain water monthly to prevent salt buildup.",
        'season': "Active October to March; with a grow light can flower year-round. Each bloom cluster lasts 4 to 6 weeks; deadhead spent flowers to encourage more. Repot annually in spring into a slightly larger pot (African Violets like a snug pot, but soil exhaustion is the limit). Use African Violet potting mix (light, peat-based, with perlite). Propagation by leaf cutting: pluck a healthy leaf with its stalk, push the stalk into damp soil, cover with a clear bag; tiny plantlets emerge in 6 to 10 weeks.",
        'trouble': "No flowers: not enough light (move closer to window or use grow light), or hungry (feed weakly weekly), or wrong fertiliser (use African Violet specific). Yellow leaves: overwatered or water-on-leaf damage. Pale ring spots on leaves: cold water touched them; trim damaged leaves, switch to room-temperature water. Brown crispy edges: low humidity or salt buildup. Powdery white spots on leaves: powdery mildew from stagnant air; improve airflow. Mealybugs and cyclamen mites: cyclamen mites are tiny and cause twisted distorted new growth; treat with miticide or discard severely infested plants. Non-toxic to pets, one of the safest flowering houseplants.",
    },
}

PATH = Path(__file__).resolve().parent.parent / 'src' / 'speciesDb.ts'

def main():
    src = PATH.read_text()
    inserted = 0
    skipped = 0

    for species_id, deep in DEEP_GUIDES.items():
        # Find the species block
        id_pattern = re.compile(r"(\s+\{\s*\n\s+id: '" + re.escape(species_id) + r"',[\s\S]*?defaultMood:.*?\n\s+\},)", re.MULTILINE)
        match = id_pattern.search(src)
        if not match:
            print(f"  ! could not find block for {species_id}", file=sys.stderr)
            continue
        block = match.group(1)
        if 'careGuideDeep' in block:
            skipped += 1
            continue

        # Build the careGuideDeep string in the same indentation as careGuide
        deep_str = (
            "    careGuideDeep: {\n"
            f"      light: {repr_js(deep['light'])},\n"
            f"      water: {repr_js(deep['water'])},\n"
            f"      food: {repr_js(deep['food'])},\n"
            f"      season: {repr_js(deep['season'])},\n"
            f"      trouble: {repr_js(deep['trouble'])},\n"
            "    },\n"
        )

        # Insert careGuideDeep right after the closing careGuide brace.
        # The careGuide block ends with "    },\n" followed by either defaultMood or another field.
        # We need to insert after the "    },\n" that closes careGuide specifically.
        # Pattern: find within the species block the careGuide closing brace.
        care_close = re.compile(r"(careGuide: \{[\s\S]*?\n    \},\n)")
        new_block = care_close.sub(lambda m: m.group(1) + deep_str, block, count=1)
        if new_block == block:
            print(f"  ! could not find careGuide close for {species_id}", file=sys.stderr)
            continue

        src = src.replace(block, new_block, 1)
        inserted += 1
        print(f"  + {species_id}")

    PATH.write_text(src)
    print(f"\nInserted {inserted}, skipped (already had careGuideDeep) {skipped}")

def repr_js(s: str) -> str:
    """Render a Python string as a TypeScript single-quoted string literal.
    Escapes single quotes and backslashes. Preserves apostrophes inside via escape.
    """
    s = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"

if __name__ == '__main__':
    main()
