// OutFlourish species library — restructured per designer's data contract.
// To add a species, append an entry to SPECIES_DB. The Plant Detail screen
// renders every field automatically.

import type { LightLevel } from './store'

export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced'
export type Humidity   = 'Low' | 'Medium' | 'High'
export type ToxicTo    = 'pets' | 'children' | 'both'

export interface CareGuide {
  light:   string
  water:   string
  food:    string
  season:  string
  trouble: string
}

export interface SpeciesProfile {
  /** Stable kebab-case id. Used as a foreign key from Plant.speciesId. Never change once published. */
  id: string
  /** Common name. Displayed in italic across the app. */
  name: string
  /** Latin binomial. Shown beneath the common name. */
  scientificName: string
  /** Alternate names for search (case-insensitive substring match). */
  aliases: string[]
  /** Relative path to bundled photo (e.g. `/species/monstera-deliciosa.jpg`)
   *  OR full Unsplash CDN URL while we bootstrap. The download script in
   *  scripts/fetch-species-photos.mjs will materialise these locally. */
  photo: string
  baseIntervalDays: number
  recommendedMl: number
  winterMl: number
  difficulty: Difficulty
  humidity: Humidity
  light: LightLevel
  toxic: boolean
  toxicTo?: ToxicTo
  careGuide: CareGuide
  /** Optional anthropomorphic line shown when adding this species. */
  defaultMood?: string
}

// ─── The library ─────────────────────────────────────────────────────────────

export const SPECIES_DB: SpeciesProfile[] = [
  {
    id: 'monstera-deliciosa',
    name: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    aliases: ['Swiss Cheese Plant', 'Split-leaf Philodendron'],
    photo: '/species/monstera-deliciosa.jpg',
    baseIntervalDays: 10,
    recommendedMl: 240,
    winterMl: 160,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect light. Morning sun is fine; harsh afternoon sun scorches the leaves. About a metre from an east-facing window is ideal.',
      water: 'When the top 3–4cm of soil is dry. About 240 ml — water steadily until you see drainage from the bottom of the pot. Drowning is the more common death than letting it dry out. Trust the meter, not the calendar.',
      food: 'Half-strength balanced liquid feed every 4 weeks from October to March. Off the menu in autumn and winter.',
      season: 'Peak growth Oct–Mar. Slows in cool months — dial water back to ~160 ml and extend interval by 30% through June and July. Wipe leaves monthly for light.',
      trouble: 'Yellow leaves → overwatered. Brown crispy edges → low humidity or thirst. No fenestrations → wants more light or maturity.',
    },
    defaultMood: 'Brooding magnificently in the corner.',
  },
  {
    id: 'fiddle-leaf-fig',
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    aliases: ['FLF'],
    photo: '/species/fiddle-leaf-fig.jpg',
    baseIntervalDays: 7,
    recommendedMl: 360,
    winterMl: 240,
    difficulty: 'Advanced',
    humidity: 'Medium',
    light: 'bright',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect light, consistent placement. Will protest any move with leaf drops. Find a happy spot and leave it.',
      water: 'When the top 3–4cm is dry. About 360 ml — water until drainage. Drooping = thirsty. Spotting + drooping = root rot. The meter tells you which.',
      food: 'High-nitrogen liquid feed monthly Oct–Mar. Essential for the big leaves.',
      season: 'Reduce watering 20% in winter. Clean leaves with a damp cloth monthly — dust shades them unfairly.',
      trouble: 'Brown spots → fungal or root rot. Leaf drop → moved or cold draft. Yellowing → overwatered.',
    },
    defaultMood: 'Stoic. Easily offended.',
  },
  {
    id: 'peace-lily',
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum wallisii',
    aliases: ['White Sails'],
    photo: '/species/peace-lily.jpg',
    baseIntervalDays: 5,
    recommendedMl: 250,
    winterMl: 180,
    difficulty: 'Beginner',
    humidity: 'High',
    light: 'low',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Low to medium indirect light. One of the best for darker rooms. Avoid direct sun.',
      water: 'When the leaves just start to droop (before full wilt). About 250 ml until drainage. Likes consistency — keep lightly moist.',
      food: 'Half-strength balanced feed every 6 weeks Oct–Mar. Too much fertiliser = browning leaf tips.',
      season: 'Big drinker in summer (every 3–4 days). Dial back in winter. Filtered water — sensitive to fluoride.',
      trouble: 'Brown leaf tips → tap-water fluoride or low humidity. Drooping despite moist soil → root rot. Not flowering → needs more light.',
    },
    defaultMood: 'Quietly dramatic about hydration.',
  },
  {
    id: 'snake-plant-laurentii',
    name: 'Snake Plant Laurentii',
    scientificName: "Dracaena trifasciata 'Laurentii'",
    aliases: ['Sansevieria', "Mother-in-Law's Tongue"],
    photo: '/species/snake-plant-laurentii.jpg',
    baseIntervalDays: 14,
    recommendedMl: 180,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Low',
    light: 'low',
    toxic: true,
    toxicTo: 'pets',
    careGuide: {
      light: 'Tolerates almost any light, from very low to bright indirect. Direct sun is possible but causes yellowing.',
      water: 'When the soil is completely dry. About 180 ml. One of the most drought-tolerant houseplants. In winter, water as rarely as once per month.',
      food: 'Once in spring and once in summer with balanced fertiliser. Bare minimum.',
      season: 'Practically dormant in winter — barely water (~100 ml every 3–4 weeks). Resume normal care October.',
      trouble: 'Mushy leaves → overwatered (the only real risk). Brown crispy tips → cold draft. Yellowing → too much sun or too much water.',
    },
    defaultMood: 'Unflappable. Will outlive your lease.',
  },
  {
    id: 'golden-pothos',
    name: 'Golden Pothos',
    scientificName: 'Epipremnum aureum',
    aliases: ["Devil's Ivy", 'Pothos'],
    photo: '/species/golden-pothos.jpg',
    baseIntervalDays: 7,
    recommendedMl: 150,
    winterMl: 90,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Tolerates low to bright indirect light. Avoid direct sun — scorches leaves.',
      water: 'When the top 2–3cm of soil is dry. About 150 ml until drainage. Drooping leaves = thirsty (not overwatered).',
      food: 'Balanced liquid fertiliser every 4 weeks in spring/summer. Skip autumn and winter.',
      season: 'Summers: water every 5–6 days. Move away from heating vents in winter — dry air causes brown tips. Reduce to every 10–14 days in winter.',
      trouble: 'Yellow leaves → overwatering. Brown tips → low humidity or fluoride in tap water. Leggy vines → insufficient light.',
    },
    defaultMood: 'Reliably enthusiastic, like a golden retriever.',
  },
  {
    id: 'hoya-kerrii',
    name: 'Hoya Kerrii',
    scientificName: 'Hoya kerrii',
    aliases: ['Sweetheart Hoya', 'Lucky Heart', 'Valentine Hoya'],
    photo: '/species/hoya-kerrii.jpg',
    baseIntervalDays: 14,
    recommendedMl: 120,
    winterMl: 80,
    difficulty: 'Beginner',
    humidity: 'Low',
    light: 'bright',
    toxic: false,
    careGuide: {
      light: 'Bright indirect light. Tolerates a little direct morning sun. Single-leaf cuttings need stable, gentle conditions.',
      water: 'Every 10–14 days. About 120 ml. The waxy leaves store water — overwater and they rot.',
      food: 'Every 4–6 weeks spring/summer with diluted balanced fertiliser.',
      season: 'Very drought tolerant. Reduce to monthly watering in winter. Will survive near a sunny window year-round.',
      trouble: 'Yellowing leaves → overwatering. Wrinkled leaves → underwatered — give a thorough soak. Not growing → single-leaf cuttings lack a node, so growth is impossible.',
    },
    defaultMood: 'Quietly affectionate. Stores water in her hearts.',
  },

  // ─── Batch 1 expansion · indoor foliage ─────────────────────────────────────

  {
    id: 'pothos-marble-queen',
    name: 'Marble Queen Pothos',
    scientificName: 'Epipremnum aureum',
    aliases: ['Marble Queen', 'Variegated Pothos'],
    photo: '',
    baseIntervalDays: 8,
    recommendedMl: 150,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect. Variegation fades in low light and scorches in direct sun. A north or east-facing window suits her.',
      water: 'When the top 3 cm dries out. About 150 ml, watered until drainage. She tells the truth — leaves droop when thirsty and perk up within hours of watering.',
      food: 'Half-strength balanced feed monthly through the growing months. Pause from June to August.',
      season: 'Slow growth in winter. Dial back to fortnightly watering. Wipe leaves occasionally to keep variegation showing.',
      trouble: 'Loss of white in new leaves → not enough light. Yellow leaves → soggy roots, ease off. Brown leaf tips → tap water salts or low humidity.',
    },
    defaultMood: 'Statuesque. Trails like she means it.',
  },
  {
    id: 'pothos-njoy',
    name: "N'Joy Pothos",
    scientificName: 'Epipremnum aureum',
    aliases: ["N'Joy", 'NJoy Pothos'],
    photo: '',
    baseIntervalDays: 9,
    recommendedMl: 120,
    winterMl: 80,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect — more light than her green cousins, to hold the crisp white patches.',
      water: 'Allow the top half of the pot to dry. About 120 ml. She forgives a forgotten week more than she forgives a soaking.',
      food: 'Diluted balanced feed every 4 weeks in growing months.',
      season: 'Growth slows by 50% in winter. Stretch waterings to 14 days and skip the feed.',
      trouble: 'Reverting to plain green sections → trim them off, they grow faster than the variegated. Crispy edges → underwatered or too much sun.',
    },
    defaultMood: 'Polite. Holds her shape neatly.',
  },
  {
    id: 'pothos-neon',
    name: 'Neon Pothos',
    scientificName: 'Epipremnum aureum',
    aliases: ['Chartreuse Pothos'],
    photo: '',
    baseIntervalDays: 8,
    recommendedMl: 150,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Brighter light keeps her chartreuse glow. In low light she turns greener and the colour drains.',
      water: 'Top 3 cm dry before watering. The chartreuse leaves darken slightly when thirsty — a useful tell.',
      food: 'Monthly half-strength feed October to March.',
      season: 'Slows considerably in cold rooms. Move away from window draughts in winter.',
      trouble: 'Pale, washed-out leaves → too much direct sun. Dark green new growth → not enough light.',
    },
    defaultMood: 'Glowing in the corner like a small radioactive event.',
  },
  {
    id: 'philodendron-brasil',
    name: 'Heartleaf Philodendron Brasil',
    scientificName: 'Philodendron hederaceum',
    aliases: ['Philodendron Brasil', 'Brasil', 'Sweetheart Vine'],
    photo: '',
    baseIntervalDays: 9,
    recommendedMl: 140,
    winterMl: 95,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect for the boldest yellow streak down the middle. Tolerates lower light but the variegation pales.',
      water: 'When the top third of soil is dry. About 140 ml — she likes a thorough drink then a slight dry-out.',
      food: 'Half-strength liquid feed every 4 weeks while growing.',
      season: 'Steady through autumn and winter if kept warm. Drop watering frequency by a third in cool months.',
      trouble: 'Long gap between leaves → reaching for light, move closer to a window. Black leaf stems → root rot, repot in fresh dry mix.',
    },
    defaultMood: 'Gentle and forgiving. Trails toward whoever is nearby.',
  },
  {
    id: 'philodendron-birkin',
    name: 'Philodendron Birkin',
    scientificName: 'Philodendron hybrid',
    aliases: ['Birkin', 'White Wave'],
    photo: '',
    baseIntervalDays: 8,
    recommendedMl: 160,
    winterMl: 110,
    difficulty: 'Intermediate',
    humidity: 'High',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect — the pinstripes lose definition in dim corners. No direct sun.',
      water: 'Keep the top 2 cm moist, not waterlogged. She prefers consistency above all else.',
      food: 'Balanced feed at quarter strength every 3 weeks in spring and summer.',
      season: 'Slows through winter. A pebble tray nearby helps when home heating dries the air.',
      trouble: 'New leaves all green → low light. Brown leaf edges → low humidity or chlorine in tap water (try filtered).',
    },
    defaultMood: 'Precise. Each leaf a fresh argument.',
  },
  {
    id: 'philodendron-pink-princess',
    name: 'Philodendron Pink Princess',
    scientificName: 'Philodendron erubescens',
    aliases: ['Pink Princess', 'PPP'],
    photo: '',
    baseIntervalDays: 10,
    recommendedMl: 180,
    winterMl: 120,
    difficulty: 'Advanced',
    humidity: 'High',
    light: 'bright',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect, edging toward filtered direct morning. The pink fades in low light and reverts toward dark green.',
      water: 'Top 3 cm dry, then water thoroughly. Sensitive to both extremes — neither bone-dry nor sodden.',
      food: 'Diluted balanced feed fortnightly in growing months. Hold back in winter entirely.',
      season: 'Likes warmth year-round. Below 16°C she sulks and stops producing new pink.',
      trouble: 'No pink in new leaves → cut back the all-green half-moon leaves to coax variegation forward. Drooping → check the soil moisture before adding more water.',
    },
    defaultMood: 'Theatrical. Lives for the new-leaf reveal.',
  },
  {
    id: 'zz-plant',
    name: 'ZZ Plant',
    scientificName: 'Zamioculcas zamiifolia',
    aliases: ['ZZ', 'Zanzibar Gem', 'Eternity Plant'],
    photo: '',
    baseIntervalDays: 14,
    recommendedMl: 180,
    winterMl: 110,
    difficulty: 'Beginner',
    humidity: 'Low',
    light: 'low',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Tolerates almost anything except direct sun. Happiest in medium indirect but will sit in a dim hall for years.',
      water: 'Soak then forget. Wait until the soil is fully dry before the next drink. Underground rhizomes store reserves.',
      food: 'Quarter-strength feed every 6 weeks in growing months. She rarely asks for more.',
      season: 'Reduce watering to once a month in winter. Truly the most forgiving plant in the home.',
      trouble: 'Yellow stems → almost always overwatering. Wrinkled stems → unusually, underwatered.',
    },
    defaultMood: 'Unbothered. Could outlive you.',
  },
  {
    id: 'chinese-evergreen',
    name: 'Chinese Evergreen',
    scientificName: 'Aglaonema commutatum',
    aliases: ['Aglaonema', 'Silver Bay'],
    photo: '',
    baseIntervalDays: 10,
    recommendedMl: 180,
    winterMl: 120,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'low',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Low to medium indirect. Patterned varieties want a touch more light to keep their patterns sharp.',
      water: 'Top 3 cm dry between waterings. About 180 ml. She is mild-tempered and tells you clearly when thirsty.',
      food: 'Diluted balanced feed monthly through warm months.',
      season: 'Slows in winter. Watch for cold spots near windows — she dislikes draughts.',
      trouble: 'Yellow edges → cold draught or chlorinated water. Drooping leaves → overwatered, pull back.',
    },
    defaultMood: 'Resilient. Has seen offices and stayed dignified.',
  },
  {
    id: 'rubber-plant',
    name: 'Rubber Plant',
    scientificName: 'Ficus elastica',
    aliases: ['Rubber Tree', 'Burgundy Rubber'],
    photo: '',
    baseIntervalDays: 10,
    recommendedMl: 280,
    winterMl: 180,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'bright',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect for deep burgundy leaves. Some morning sun is fine — afternoon direct will scorch.',
      water: 'Top 3 cm dry before watering. Drains thoroughly — never leave her sitting in water.',
      food: 'Balanced feed every 4 weeks in growing months.',
      season: 'Steady year-round in a warm room. Dial back about 30% in winter.',
      trouble: 'Dropping leaves → sudden move or cold draught. Sticky leaves → check undersides for scale insect.',
    },
    defaultMood: 'Architectural. Holds court in any room.',
  },
  {
    id: 'bird-of-paradise',
    name: 'Bird of Paradise',
    scientificName: 'Strelitzia nicolai',
    aliases: ['White Bird', 'Strelitzia'],
    photo: '',
    baseIntervalDays: 8,
    recommendedMl: 400,
    winterMl: 260,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    light: 'bright',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'As bright as you can give her — direct sun for at least 4 hours encourages flowering eventually.',
      water: 'Deep soak when the top 4 cm is dry. About 400 ml. The split leaves are normal and add to her charm.',
      food: 'Balanced feed fortnightly through October to April. Halt entirely in winter.',
      season: 'Slows but stays active. Tolerates short cool spells but recovers fastest above 18°C.',
      trouble: 'Brown crispy edges → low humidity or salt buildup in soil — flush the pot. No flowers → she needs to be root-bound and several years old.',
    },
    defaultMood: 'Grand and ungoverned. Imagines herself in a courtyard.',
  },
  {
    id: 'calathea-orbifolia',
    name: 'Calathea Orbifolia',
    scientificName: 'Goeppertia orbifolia',
    aliases: ['Orbifolia', 'Round-Leaf Calathea'],
    photo: '',
    baseIntervalDays: 5,
    recommendedMl: 220,
    winterMl: 150,
    difficulty: 'Advanced',
    humidity: 'High',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect only — direct sun bleaches the silver stripes within days.',
      water: 'Keep evenly moist with filtered or rainwater. Tap water salts give her crisp edges. About 220 ml every 5 days.',
      food: 'Quarter-strength balanced feed every 3 weeks in growing months.',
      season: 'Slows in winter but still hates dry indoor air. A humidifier or pebble tray nearby is non-negotiable in heated homes.',
      trouble: 'Crispy edges → almost always low humidity or tap water. Curling leaves → thirsty, water immediately. Stillness in new growth → too cold.',
    },
    defaultMood: 'Demanding but worth it. Conducts daily prayer with her leaves.',
  },
  {
    id: 'calathea-medallion',
    name: 'Calathea Medallion',
    scientificName: 'Goeppertia roseopicta',
    aliases: ['Medallion', 'Rose-Painted Calathea'],
    photo: '',
    baseIntervalDays: 5,
    recommendedMl: 180,
    winterMl: 120,
    difficulty: 'Advanced',
    humidity: 'High',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect. She closes her leaves at night and reopens at dawn — a small daily miracle.',
      water: 'Evenly moist. Filtered or rainwater only. About 180 ml every 5 days.',
      food: 'Diluted feed monthly in growing season.',
      season: 'Drops humidity tolerance in winter — keep her humid even when watering less.',
      trouble: 'Curling leaves → thirsty or cold. Yellow lower leaves → overwatered or stagnant air. Brown edges → tap water, switch sources.',
    },
    defaultMood: 'Folds her leaves at night like she means it.',
  },
  {
    id: 'spider-plant',
    name: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    aliases: ['Airplane Plant', 'Ribbon Plant'],
    photo: '',
    baseIntervalDays: 8,
    recommendedMl: 160,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect best, but tolerates a wide range. Variegation fades in dim corners.',
      water: 'Top 2 cm dry before watering. Sensitive to fluoride in tap water — leave water out overnight or use filtered.',
      food: 'Half-strength balanced feed monthly. Too much fertiliser stops her producing babies.',
      season: 'Steady through winter. Produces flower stalks and pups in spring — pot these up or leave them dangling.',
      trouble: 'Brown leaf tips → fluoride or fertiliser buildup, flush the pot. No babies → may need to be root-bound and given longer days.',
    },
    defaultMood: 'Generous. Always making babies, never asks for thanks.',
  },
  {
    id: 'boston-fern',
    name: 'Boston Fern',
    scientificName: 'Nephrolepis exaltata',
    aliases: ['Sword Fern'],
    photo: '',
    baseIntervalDays: 4,
    recommendedMl: 200,
    winterMl: 140,
    difficulty: 'Intermediate',
    humidity: 'High',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect or filtered morning sun. Dappled shade outdoors in summer suits her.',
      water: 'Keep evenly moist, never dry. Daily misting in heated rooms. The dropped fronds tell you she is too dry.',
      food: 'Quarter-strength feed every 2 weeks in growing months.',
      season: 'Difficult in winter heating. Bathroom or kitchen humidity helps. Trim browned fronds at the base.',
      trouble: 'Brown crispy fronds → too dry or too hot. Yellowing → too wet, ease off. Constant shedding → low humidity, normal but reducible.',
    },
    defaultMood: 'Highly strung. Performs best in steam.',
  },
  {
    id: 'maidenhair-fern',
    name: 'Maidenhair Fern',
    scientificName: 'Adiantum raddianum',
    aliases: ['Maidenhair'],
    photo: '',
    baseIntervalDays: 3,
    recommendedMl: 120,
    winterMl: 90,
    difficulty: 'Advanced',
    humidity: 'High',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Soft indirect light. Anything direct burns her delicate fronds within an hour.',
      water: 'Never let her dry out — she will crash dramatically and may not recover. Filtered water at room temperature.',
      food: 'Very weak feed monthly in growing months. Strong fertiliser will scorch her roots.',
      season: 'Year-round attention. Lift her into the bathroom while you shower for a humidity boost.',
      trouble: 'All fronds gone crispy → she dried out, cut everything back to the base and keep watering, new fronds may emerge.',
    },
    defaultMood: 'Wildly dramatic. Hates being touched.',
  },
  {
    id: 'parlor-palm',
    name: 'Parlor Palm',
    scientificName: 'Chamaedorea elegans',
    aliases: ['Neanthe Bella', 'Parlour Palm'],
    photo: '',
    baseIntervalDays: 10,
    recommendedMl: 200,
    winterMl: 130,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'low',
    toxic: false,
    careGuide: {
      light: 'Low to medium indirect. Direct sun yellows the fronds.',
      water: 'Top 3 cm dry before watering. Drain thoroughly. She prefers slightly dry over slightly wet.',
      food: 'Diluted balanced feed every 6 weeks in growing months.',
      season: 'Slows considerably below 18°C. Reduce watering by half and stop feeding.',
      trouble: 'Brown frond tips → low humidity or salty water. Yellow fronds → overwatering. Slow growth → normal, she takes her time.',
    },
    defaultMood: 'Victorian. Stands beside a chesterfield in spirit.',
  },
  {
    id: 'kentia-palm',
    name: 'Kentia Palm',
    scientificName: 'Howea forsteriana',
    aliases: ['Thatch Palm', 'Sentry Palm'],
    photo: '',
    baseIntervalDays: 10,
    recommendedMl: 350,
    winterMl: 230,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect. Tolerates lower light than most palms, which is why she ends up in hotel lobbies.',
      water: 'Top 3 cm dry, then water thoroughly. Sensitive to chlorine — let tap water sit a day if your water is treated.',
      food: 'Balanced palm feed monthly from October to March.',
      season: 'Slows in winter. Cut watering to every 14 days and stop feeding entirely.',
      trouble: 'Yellow fronds → overwatering, the most common death. Brown tips → low humidity or salts. Spider mites in dry air → mist undersides and wipe.',
    },
    defaultMood: 'Quietly grand. Lifts a room without trying.',
  },

  // ─── Succulents & cacti ─────────────────────────────────────────────────────

  {
    id: 'jade-plant',
    name: 'Jade Plant',
    scientificName: 'Crassula ovata',
    aliases: ['Money Tree', 'Money Plant', 'Lucky Plant'],
    photo: '',
    baseIntervalDays: 14,
    recommendedMl: 120,
    winterMl: 60,
    difficulty: 'Beginner',
    humidity: 'Low',
    light: 'bright',
    toxic: true,
    toxicTo: 'pets',
    careGuide: {
      light: 'Bright direct sun. A south-facing window suits her. Insufficient light makes her leggy and pale.',
      water: 'Drench-and-dry. Soak thoroughly, then wait until the soil is fully dry — usually 14 days. Less in winter.',
      food: 'Cactus feed at half strength every 2 months in growing season.',
      season: 'Reduce watering to once a month in winter. Cooler nights and dry soil can coax small pink-white flowers.',
      trouble: 'Wrinkled leaves → underwatered, give a soak. Mushy stem at base → overwatered, repot in dry mix and cut off rot.',
    },
    defaultMood: 'Stoic and slow. Lives to be inherited.',
  },
  {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    aliases: ['True Aloe', 'Medicinal Aloe'],
    photo: '',
    baseIntervalDays: 14,
    recommendedMl: 180,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Low',
    light: 'bright',
    toxic: true,
    toxicTo: 'pets',
    careGuide: {
      light: 'Direct sun for at least 6 hours. South-facing windowsill is ideal. Bright light keeps her thick and compact.',
      water: 'Soak thoroughly, then let the soil go bone dry. Her plump leaves are the reservoir.',
      food: 'Cactus feed quarterly. Easy to overdo it.',
      season: 'Once a month in winter is plenty. Cold-tolerant down to 5°C briefly but unhappy below 13°C.',
      trouble: 'Brown thin leaves → too much sun or sunburn. Drooping outward from the centre → overwatered. Pups around the base → divide and pot up.',
    },
    defaultMood: 'Practical. Useful for kitchen burns.',
  },
  {
    id: 'echeveria-elegans',
    name: 'Echeveria Elegans',
    scientificName: 'Echeveria elegans',
    aliases: ['Mexican Snowball', 'Hen and Chicks'],
    photo: '',
    baseIntervalDays: 14,
    recommendedMl: 80,
    winterMl: 40,
    difficulty: 'Beginner',
    humidity: 'Low',
    light: 'bright',
    toxic: false,
    careGuide: {
      light: 'Direct sun, the more the better. South-facing windowsill is her favourite real estate.',
      water: 'Soak the soil thoroughly, then leave bone dry for 2 weeks. Water from below if you can — wet rosettes rot.',
      food: 'Diluted cactus feed once or twice a year, no more.',
      season: 'Cut watering to once a month in winter. Cooler nights with bright light bring out her pink edges.',
      trouble: 'Stretching toward the window → not enough light, she will become leggy. Mushy bottom leaves → overwatering. Pups around the base → propagate them.',
    },
    defaultMood: 'Geometric and self-contained.',
  },
  {
    id: 'string-of-pearls',
    name: 'String of Pearls',
    scientificName: 'Senecio rowleyanus',
    aliases: ['Pearl Plant', 'Curio rowleyanus'],
    photo: '',
    baseIntervalDays: 14,
    recommendedMl: 100,
    winterMl: 60,
    difficulty: 'Intermediate',
    humidity: 'Low',
    light: 'bright',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect with a few hours of soft morning sun. The pearls plump up in good light.',
      water: 'Soak then dry completely. Watering from above is fine — just avoid sitting water.',
      food: 'Diluted cactus feed every 6 weeks in growing months.',
      season: 'Once a month in winter. Tiny white pom-pom flowers appear in autumn under good conditions.',
      trouble: 'Shriveled pearls → underwatered. Mushy pearls → overwatered, dial back urgently. Bald patches → broken strands, replant trimmings.',
    },
    defaultMood: 'A tumble of small green opinions.',
  },
  {
    id: 'christmas-cactus',
    name: 'Christmas Cactus',
    scientificName: 'Schlumbergera bridgesii',
    aliases: ['Holiday Cactus', 'Zygocactus'],
    photo: '',
    baseIntervalDays: 8,
    recommendedMl: 150,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect. Unlike desert cacti she dislikes harsh direct sun.',
      water: 'Top 2 cm dry between waterings. She likes more water than most cacti — her ancestors are jungle dwellers.',
      food: 'Balanced feed monthly in growing months. Stop 6 weeks before you want flowers.',
      season: 'To flower, give her 14 hours of darkness and cool nights (~13°C) for 6 weeks in autumn. She does the rest.',
      trouble: 'Dropped buds → soil dried out or she was moved during budding. No flowers → not enough dark in autumn.',
    },
    defaultMood: 'A reluctant bloomer with theatrical timing.',
  },

  // ─── Flowering houseplants ──────────────────────────────────────────────────

  {
    id: 'hoya-carnosa',
    name: 'Hoya Carnosa',
    scientificName: 'Hoya carnosa',
    aliases: ['Wax Plant', 'Porcelain Flower'],
    photo: '',
    baseIntervalDays: 12,
    recommendedMl: 160,
    winterMl: 100,
    difficulty: 'Beginner',
    humidity: 'Medium',
    light: 'bright',
    toxic: false,
    careGuide: {
      light: 'Bright indirect with some direct morning sun. Good light is the single biggest factor in getting her to flower.',
      water: 'Top half of pot dry between waterings. Her thick leaves store water — she handles a missed week better than a soggy one.',
      food: 'Diluted bloom feed every 3 weeks in growing season.',
      season: 'Reduce watering by a third in winter. Do not move her once buds appear, she will drop them.',
      trouble: 'No flowers → not enough light, or being repotted too often. Yellow leaves → overwatering. Sticky residue → sap from flower spurs (peduncles), do not cut these off — she reblooms from the same spur.',
    },
    defaultMood: 'Patient. Plots her flowers in private for months.',
  },
  {
    id: 'anthurium',
    name: 'Anthurium',
    scientificName: 'Anthurium andraeanum',
    aliases: ['Flamingo Flower', 'Lace Leaf'],
    photo: '',
    baseIntervalDays: 6,
    recommendedMl: 200,
    winterMl: 140,
    difficulty: 'Intermediate',
    humidity: 'High',
    light: 'medium',
    toxic: true,
    toxicTo: 'both',
    careGuide: {
      light: 'Bright indirect, never direct. Good light keeps her blooming nearly year-round.',
      water: 'Keep evenly moist but not wet. Top 1 cm of soil should be dry before watering.',
      food: 'Diluted bloom feed every 2 weeks in growing months.',
      season: 'Slows in winter. Reduce watering by a quarter and stop feeding.',
      trouble: 'No flowers → low light or too much fertiliser nitrogen — switch to a bloom-specific feed. Yellow leaves → overwatering. Brown leaf tips → low humidity.',
    },
    defaultMood: 'Lipstick-red and unembarrassed about it.',
  },
  {
    id: 'phalaenopsis-orchid',
    name: 'Phalaenopsis Orchid',
    scientificName: 'Phalaenopsis hybrid',
    aliases: ['Moth Orchid', 'Phal'],
    photo: '',
    baseIntervalDays: 7,
    recommendedMl: 100,
    winterMl: 80,
    difficulty: 'Intermediate',
    humidity: 'High',
    light: 'medium',
    toxic: false,
    careGuide: {
      light: 'Bright indirect, east-facing window ideal. Leaves should be a healthy mid-green — dark green means too little light.',
      water: 'Soak the bark mix once a week, then let it dry almost completely. Three ice cubes is a myth — give her a proper drink.',
      food: 'Quarter-strength orchid feed weekly while in active growth, monthly otherwise.',
      season: 'After her flowers drop, cut the spike to a node and a fresh spike may emerge. Cooler nights in autumn (~16°C) help reflower.',
      trouble: 'Yellow lower leaves → natural, she sheds the old. Wrinkled leaves → roots may be rotted, check by lifting from the pot. No new flowers → not enough light or no cool spell.',
    },
    defaultMood: 'Worth the wait. Reblooms when she feels like it.',
  },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function searchSpecies(query: string): SpeciesProfile[] {
  const q = query.trim().toLowerCase()
  if (!q) return SPECIES_DB
  return SPECIES_DB.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.scientificName.toLowerCase().includes(q) ||
    s.aliases.some(a => a.toLowerCase().includes(q)),
  )
}

export function getSpeciesById(id: string): SpeciesProfile | undefined {
  return SPECIES_DB.find(s => s.id === id)
}

export function getSpeciesByDifficulty(level: Difficulty): SpeciesProfile[] {
  return SPECIES_DB.filter(s => s.difficulty === level)
}

export function getSpeciesByLight(light: LightLevel): SpeciesProfile[] {
  return SPECIES_DB.filter(s => s.light === light)
}
