export interface SpeciesProfile {
  id: string
  name: string
  aliases: string[]
  emoji: string
  baseIntervalDays: number
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
  humidity: 'Low' | 'Medium' | 'High'
  toxic: boolean
  toxicTo?: 'pets' | 'children' | 'both'
  light: string
  watering: string
  fertilising: string
  seasonal: string
  commonProblems: string
}

export const SPECIES_DB: SpeciesProfile[] = [
  // ─── Pothos & Epipremnum ─────────────────────────────────────────────────
  {
    id: 'golden-pothos',
    name: 'Golden Pothos',
    aliases: ['Pothos', "Devil's Ivy", 'Epipremnum aureum'],
    emoji: '🌿',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Tolerates low to bright indirect light. Avoid direct sun — scorches leaves.',
    watering: 'Water when top 2–3cm of soil is dry. Drooping leaves = thirsty (not overwatered). Always use a pot with drainage holes.',
    fertilising: 'Balanced liquid fertiliser (e.g. 20-20-20) every 4 weeks in spring/summer. Skip autumn/winter.',
    seasonal: 'Melbourne summers: water every 5–6 days. Move away from heating vents in winter — dry air causes brown tips. Reduce to every 10–14 days in winter.',
    commonProblems: 'Yellow leaves: overwatering/root rot — let fully dry out. Brown tips: low humidity or fluoride in tap water — switch to filtered water. Leggy vines: insufficient light — move closer to window.',
  },
  {
    id: 'neon-pothos',
    name: 'Neon Pothos',
    aliases: ['Neon Epipremnum', 'Lime Pothos'],
    emoji: '💚',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light keeps colour vivid. Tolerates medium light but colour fades.',
    watering: 'Water when top 2cm of soil is dry. Same care as Golden Pothos — very forgiving.',
    fertilising: 'Monthly spring/summer with balanced liquid fertiliser. The bright colour is genetic, not fertiliser-dependent.',
    seasonal: 'Melbourne summers: every 5–6 days. Keep away from aircon vents. Reduce winter watering significantly.',
    commonProblems: 'Faded neon colour: move to brighter spot. Yellow leaves: overwatering. Brown leaf tips: low humidity.',
  },
  {
    id: 'marble-queen-pothos',
    name: 'Marble Queen Pothos',
    aliases: ['Marble Pothos', 'Variegated Pothos'],
    emoji: '🌱',
    baseIntervalDays: 9,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light essential to maintain variegation. In low light, leaves revert to green.',
    watering: 'Water when top 2–3cm is dry. Variegated leaves photosynthesize less efficiently — slightly drought-tolerant.',
    fertilising: 'Every 4 weeks spring/summer. Avoid high-nitrogen fertiliser — promotes green growth over variegation.',
    seasonal: 'Slower grower than Golden Pothos. Melbourne winters: water every 12–16 days. Keep above 15°C.',
    commonProblems: 'Reverting to green: increase light. Root rot: ensure pot drains well. Crispy edges: low humidity.',
  },
  {
    id: 'cebu-blue-pothos',
    name: 'Cebu Blue Pothos',
    aliases: ['Epipremnum pinnatum', 'Blue Pothos', 'Dragon Tail Pothos'],
    emoji: '🔵',
    baseIntervalDays: 8,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Will tolerate medium light but blue sheen is less pronounced.',
    watering: 'Water when top 2–3cm of soil feels dry. Allow roots to breathe between waterings.',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: grows vigorously Oct–Mar. Keep above 10°C. Protect from cold drafts near winter windows.',
    commonProblems: 'Pale leaves: needs more light. Yellowing: overwatered. To encourage fenestrations, allow the plant to mature on a pole or wall.',
  },

  // ─── Philodendrons ───────────────────────────────────────────────────────
  {
    id: 'heartleaf-philodendron',
    name: 'Heartleaf Philodendron',
    aliases: ['Philodendron hederaceum', 'Sweetheart Philodendron'],
    emoji: '💚',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Medium to bright indirect light. Tolerates low light better than most.',
    watering: 'Water when top 2–3cm is dry. Wilts dramatically when thirsty but bounces back quickly.',
    fertilising: 'Monthly spring/summer with balanced fertiliser. Dilute to half-strength.',
    seasonal: 'Melbourne summer: may need water every 5–6 days. Winter: every 10–12 days. Loves humidity — mist or pebble tray.',
    commonProblems: 'Yellow leaves: overwatering. Leggy growth: insufficient light. Drooping despite moist soil: root rot — check drainage.',
  },
  {
    id: 'philodendron-brasil',
    name: 'Philodendron Brasil',
    aliases: ['Brasil Philodendron', 'Variegated Heartleaf Philodendron'],
    emoji: '🌿',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light to maintain yellow-green variegation. Avoid low light — leaves revert to green.',
    watering: 'Water when top 2cm is dry. Consistent moisture preferred — don\'t let it dry out completely.',
    fertilising: 'Monthly spring/summer. Balanced or slightly higher nitrogen encourages lush growth.',
    seasonal: 'Melbourne: thrives in humid summer. In winter reduce watering and move away from heaters.',
    commonProblems: 'Reverted green leaves: move to brighter spot. Yellowing: overwatered. Leggy: needs more light.',
  },
  {
    id: 'velvet-philodendron',
    name: 'Velvet Philodendron',
    aliases: ['Philodendron micans', 'Iridescent Philodendron'],
    emoji: '🌑',
    baseIntervalDays: 8,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light to bring out the iridescent sheen. Avoid direct sun.',
    watering: 'Water when top 2–3cm is dry. Sensitive to both overwatering and drought.',
    fertilising: 'Monthly spring/summer at half strength. High humidity more important than fertiliser frequency.',
    seasonal: 'Melbourne: group with other plants or use a humidifier in dry summers. Protect from cold below 13°C.',
    commonProblems: 'Crispy edges: low humidity. Yellowing lower leaves: normal ageing or overwatering. Pale leaves: too much light.',
  },
  {
    id: 'philodendron-birkin',
    name: 'Philodendron Birkin',
    aliases: ['White Wave Philodendron'],
    emoji: '🌿',
    baseIntervalDays: 8,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light maintains white pinstripe variegation. Lower light dulls the pattern.',
    watering: 'Water when top 2–3cm is dry. Sensitive to overwatering — ensure excellent drainage.',
    fertilising: 'Monthly spring/summer with balanced liquid fertiliser.',
    seasonal: 'Melbourne: grow indoors year-round. Slower growing than other Philodendrons. Protect from cold.',
    commonProblems: 'Reverting to plain green: unstable variegation (normal for this cultivar). Yellowing: overwatering. Root rot: most common problem — always check soil before watering.',
  },
  {
    id: 'philodendron-gloriosum',
    name: 'Philodendron Gloriosum',
    aliases: ['Velvet Philodendron Gloriosum'],
    emoji: '🌟',
    baseIntervalDays: 10,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. The velvety leaves burn easily in direct sun.',
    watering: 'Water when top 3cm is dry. A terrestrial crawler — plant in chunky, airy mix.',
    fertilising: 'Monthly spring/summer. Worth using a fertiliser with calcium and magnesium.',
    seasonal: 'Melbourne: thrives in humid conditions. In winter reduce watering to every 14–16 days. Protect from cold drafts.',
    commonProblems: 'Yellowing: overwatering. Brown patches on leaves: direct sun burn. Slow growth: needs more humidity or warmth.',
  },

  // ─── Hoyas ───────────────────────────────────────────────────────────────
  {
    id: 'hoya-carnosa',
    name: 'Hoya Carnosa',
    aliases: ['Wax Plant', 'Porcelain Flower'],
    emoji: '🌸',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light or a few hours of gentle morning sun. Needs good light to bloom.',
    watering: 'Water when soil is almost completely dry. Semi-succulent stems store water — less is more.',
    fertilising: 'Monthly spring/summer with a fertiliser higher in phosphorus (promotes blooming).',
    seasonal: 'Melbourne: can tolerate a drier winter — water every 14–18 days. Blooms appear in spring after a cooler, drier winter rest.',
    commonProblems: 'No flowers: needs more light and a cooler winter rest. Yellowing waxy leaves: root rot — repot in well-draining mix. Dropping leaves: cold drafts or sudden temperature change.',
  },
  {
    id: 'hoya-kerrii',
    name: 'Hoya Kerrii',
    aliases: ['Sweetheart Hoya', 'Valentine Hoya', 'Lucky Heart'],
    emoji: '💖',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Bright indirect light. Tolerates a little direct morning sun.',
    watering: 'Water every 10–14 days. Single-leaf cuttings (sold as novelties) rarely grow further — buy a full vine for growth.',
    fertilising: 'Every 4–6 weeks spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: very drought tolerant. Reduce to monthly watering in winter. Will survive near a sunny window year-round.',
    commonProblems: 'Yellowing leaves: overwatering. Wrinkled leaves: underwatered — give a thorough soak. Not growing: single-leaf cuttings lack a node, so growth is impossible.',
  },
  {
    id: 'hoya-australis',
    name: 'Hoya Australis',
    aliases: ['Australian Wax Plant', 'Hoya australis'],
    emoji: '🌺',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. One of the most light-tolerant Hoyas — tolerates some direct sun.',
    watering: 'Water when top half of soil is dry. Allow to nearly dry out in winter.',
    fertilising: 'Monthly spring/summer. Phosphorus-rich fertiliser encourages the beautifully fragrant flowers.',
    seasonal: 'Melbourne: a local favourite — native to Australia. Grows fast in warm months. Winter rest improves spring flowering. Can tolerate outdoors in a sheltered spot over summer.',
    commonProblems: 'No blooms: needs bright light and a cool winter rest period. Yellow leaves: overwatering. Brown peduncles: do not remove — flowers regrow from same spurs.',
  },
  {
    id: 'hoya-pubicalyx',
    name: 'Hoya Pubicalyx',
    aliases: ['Pink Silver Hoya', 'Splash Hoya'],
    emoji: '✨',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Silver splash pattern more prominent with good light.',
    watering: 'Water when top 3–4cm is dry. Very forgiving — tolerates occasional neglect.',
    fertilising: 'Monthly spring/summer. Potassium-rich fertiliser helps promote blooms.',
    seasonal: 'Melbourne: can handle brief periods outdoors in a sheltered, shaded spot in summer. Winter: every 14 days.',
    commonProblems: 'Fading silver splashes: needs more light. Yellowing: overwatering. No blooms: needs bright light and a slight winter rest.',
  },

  // ─── Strings ─────────────────────────────────────────────────────────────
  {
    id: 'string-of-pearls',
    name: 'String of Pearls',
    aliases: ['Senecio rowleyanus', 'Curio rowleyanus'],
    emoji: '🫧',
    baseIntervalDays: 14,
    difficulty: 'Intermediate',
    humidity: 'Low',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light — at least 4 hours near a window. Some direct morning sun is fine.',
    watering: 'Water thoroughly when soil is completely dry. Overwatering is the #1 cause of death — the pearls rot very quickly. Water from below by sitting pot in water for 10 minutes.',
    fertilising: 'Once in spring and once in early summer with diluted succulent fertiliser. Never in autumn/winter.',
    seasonal: 'Melbourne: summer heat can stress this plant — move to bright but cooler spot. In winter barely water (once per month). Protect from frost.',
    commonProblems: 'Shrivelled pearls: underwatered — soak the pot. Mushy pearls: overwatered/root rot — repot in dry soil. Leggy with gaps: insufficient light. Fast die-off at base: stem rot — trim and propagate healthy sections.',
  },
  {
    id: 'string-of-hearts',
    name: 'String of Hearts',
    aliases: ['Ceropegia woodii', 'Rosary Vine', 'Chain of Hearts'],
    emoji: '💗',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Bright indirect light with some direct sun to maintain pink/purple tones on leaves.',
    watering: 'Water when soil is mostly dry. Tubers store water — very drought-tolerant.',
    fertilising: 'Monthly spring/summer with diluted succulent fertiliser.',
    seasonal: 'Melbourne: prolific grower in spring/summer. Reduce to every 2 weeks in winter. Tolerates cooler temps than most trailing plants.',
    commonProblems: 'Faded pink colour: move to brighter spot with morning sun. Wilting despite moist soil: root rot. Sparse vines: needs more light or fertiliser in growing season.',
  },
  {
    id: 'string-of-dolphins',
    name: 'String of Dolphins',
    aliases: ['Senecio peregrinus', 'Flying Dolphins Plant'],
    emoji: '🐬',
    baseIntervalDays: 14,
    difficulty: 'Intermediate',
    humidity: 'Low',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Avoid direct harsh afternoon sun which burns the dolphin-shaped leaves.',
    watering: 'Water when soil is completely dry. Prone to root rot — ensure excellent drainage.',
    fertilising: 'Once in spring with diluted succulent fertiliser. Over-fertilising causes leaves to lose their dolphin shape.',
    seasonal: 'Melbourne: prefers cooler, brighter conditions than String of Pearls. Keep below 25°C if possible. Almost no water in winter.',
    commonProblems: 'Leaves losing dolphin shape: over-fertilised or insufficient light. Mushy stems: root rot — reduce watering immediately. Shrivelling: underwatered or summer heat stress.',
  },

  // ─── Tradescantia ────────────────────────────────────────────────────────
  {
    id: 'tradescantia-zebrina',
    name: 'Tradescantia Zebrina',
    aliases: ['Wandering Dude', 'Wandering Jew', 'Spiderwort'],
    emoji: '💜',
    baseIntervalDays: 5,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'pets',
    light: 'Bright indirect light to maintain purple/silver stripe colour. Too little light turns leaves plain green.',
    watering: 'Water when top 2cm is dry. Fast grower — drinks more than you expect. Keep consistently moist (but not waterlogged).',
    fertilising: 'Every 2–3 weeks spring/summer with balanced fertiliser. Trim regularly to keep bushy.',
    seasonal: 'Melbourne: grows extremely fast in warm months — trim and propagate cuttings. In winter growth slows, reduce watering to every 7–10 days.',
    commonProblems: 'Faded colour/green leaves: needs more light. Leggy bare stems: normal — trim 1/3 regularly and propagate. Root rot: easy to propagate from cuttings if root rot occurs.',
  },

  // ─── Aroids ──────────────────────────────────────────────────────────────
  {
    id: 'monstera-deliciosa',
    name: 'Monstera Deliciosa',
    aliases: ['Swiss Cheese Plant', 'Monstera'],
    emoji: '🌱',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Morning direct sun OK. Avoid harsh western afternoon sun.',
    watering: 'Water when top 3–4cm of soil is dry. Overwatering is the #1 cause of death. Always check soil before watering.',
    fertilising: 'Monthly spring/summer with balanced liquid fertiliser at half strength. Stop in winter.',
    seasonal: 'Peak growth Oct–Mar in Melbourne. Winter: growth stops — cut watering significantly. Wipe leaves monthly to maximise light absorption.',
    commonProblems: 'No fenestrations: insufficient light or immaturity. Yellow leaves: overwatering. Brown crispy edges: underwatering or low humidity — mist 2x per week.',
  },
  {
    id: 'monstera-adansonii',
    name: 'Monstera Adansonii',
    aliases: ['Swiss Cheese Vine', 'Five Holes Plant'],
    emoji: '🕳️',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Fenestrations increase with more light.',
    watering: 'Water when top 2–3cm is dry. Likes consistency — don\'t let it dry out completely.',
    fertilising: 'Monthly spring/summer. Loves humidity more than fertiliser.',
    seasonal: 'Melbourne: thrives on a moss pole. In summer, mist daily or use a humidifier. Reduce watering in winter.',
    commonProblems: 'Small leaves without holes: insufficient light or immature. Yellowing: overwatering. Brown edges: low humidity — use a pebble tray.',
  },
  {
    id: 'mini-monstera',
    name: 'Mini Monstera',
    aliases: ['Rhaphidophora tetrasperma', 'Ginny Philodendron', 'Piccolo'],
    emoji: '🌿',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Grows faster with more light.',
    watering: 'Water when top 2–3cm is dry. Likes to be slightly moist — don\'t let it dry fully.',
    fertilising: 'Every 3–4 weeks spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: extremely fast grower in summer — can grow several leaves per week with good conditions. Needs support to climb. Winter: slow to dormant.',
    commonProblems: 'Yellowing: overwatering or root-bound. Leggy with no fenestrations: needs more light and a pole to climb. Crispy tips: low humidity.',
  },
  {
    id: 'peace-lily',
    name: 'Peace Lily',
    aliases: ['Spathiphyllum', 'White Sails'],
    emoji: '🤍',
    baseIntervalDays: 5,
    difficulty: 'Beginner',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Low to medium indirect light. One of the best plants for low-light rooms.',
    watering: 'Water when leaves just start to droop (before full wilt). Likes consistency — keep lightly moist.',
    fertilising: 'Every 6 weeks spring/summer with balanced fertiliser at half strength.',
    seasonal: 'Melbourne: dramatic drooper in summer heat — may need water every 3–4 days. In winter let soil dry slightly between waterings.',
    commonProblems: 'Brown leaf tips: fluoride in tap water or low humidity — use filtered water. Drooping despite moist soil: overwatered/root rot. Not flowering: needs brighter light.',
  },
  {
    id: 'aglaonema',
    name: 'Chinese Evergreen',
    aliases: ['Aglaonema', 'Painted Drop Tongue'],
    emoji: '🔴',
    baseIntervalDays: 8,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Adapts to low to bright indirect light. Red/pink varieties need brighter light for colour.',
    watering: 'Water when top 3cm is dry. Very tolerant — one of the toughest houseplants.',
    fertilising: 'Every 6–8 weeks spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: extremely cold-sensitive — keep above 15°C. Move away from cold windows in winter. Drought tolerant in winter.',
    commonProblems: 'Fading colour: more light needed for red/pink varieties. Yellow leaves: overwatering or cold drafts. Brown tips: fluoride in water or low humidity.',
  },
  {
    id: 'dieffenbachia',
    name: 'Dieffenbachia',
    aliases: ['Dumb Cane', 'Leopard Lily'],
    emoji: '🌿',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Medium to bright indirect light. Tolerates low light but grows slowly.',
    watering: 'Water when top 3cm is dry. Sensitive to fluoride — use filtered or rainwater.',
    fertilising: 'Monthly spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: keep above 15°C. Reduce watering in winter. Avoid cold windows.',
    commonProblems: 'Yellowing lower leaves: normal ageing or overwatering. Brown tips: fluoride toxicity — switch to rainwater. Drooping: underwatered or cold stress.',
  },
  {
    id: 'alocasia-polly',
    name: 'Alocasia Polly',
    aliases: ['Elephant Ear', 'African Mask Plant', 'Alocasia amazonica Polly'],
    emoji: '🎭',
    baseIntervalDays: 7,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Cannot tolerate direct sun or low light.',
    watering: 'Water when top 2–3cm is dry. Sensitive — keep slightly moist but never waterlogged.',
    fertilising: 'Every 3–4 weeks spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: goes dormant in winter — may lose all leaves. This is normal. Reduce watering drastically. New growth returns in spring. Keep above 18°C.',
    commonProblems: 'Drooping leaves: underwatered, root rot, or temperature stress. Yellow leaves: overwatering or direct sun. Dormancy in winter: normal — don\'t discard. Spider mites: common in dry conditions — mist regularly.',
  },
  {
    id: 'alocasia-zebrina',
    name: 'Alocasia Zebrina',
    aliases: ['Zebra Alocasia', 'Elephant Ear Zebrina'],
    emoji: '🦓',
    baseIntervalDays: 7,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. The striking zebra-patterned stems need good light to shine.',
    watering: 'Water when top 2–3cm is dry. Very sensitive to root rot — use a chunky, well-draining mix.',
    fertilising: 'Monthly spring/summer. Less is more — avoid over-fertilising.',
    seasonal: 'Melbourne: a true tropical — keep above 18°C at all times. May lose leaves in winter. High humidity is essential year-round.',
    commonProblems: 'Yellowing leaves: overwatering. Dormancy: normal in Melbourne winters. Drooping: check soil moisture and room temperature. Spider mites: inspect regularly.',
  },
  {
    id: 'caladium',
    name: 'Caladium',
    aliases: ['Angel Wings', 'Elephant Ear Caladium', 'Heart of Jesus'],
    emoji: '🫀',
    baseIntervalDays: 5,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light for colourful varieties. Tolerates lower light (leaves become more green).',
    watering: 'Keep consistently moist during growing season. Allow to dry slightly in autumn — the tuber goes dormant.',
    fertilising: 'Every 2 weeks spring/summer with diluted balanced fertiliser to support the large colourful leaves.',
    seasonal: 'Melbourne: goes fully dormant in autumn/winter. Let the soil dry completely, store tuber dry and cool, replant in October. Lush growth returns in spring.',
    commonProblems: 'Leaf collapse: overwatered or root rot. Faded colours: low light. Dormancy in April: completely normal — this is its natural cycle.',
  },
  {
    id: 'anthurium',
    name: 'Anthurium',
    aliases: ['Flamingo Flower', 'Laceleaf', 'Anthurium andraeanum'],
    emoji: '❤️',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Direct sun bleaches the spathe and burns leaves.',
    watering: 'Water when top 3cm is dry. Sensitive to both overwatering and drought — water thoroughly then allow to partially dry.',
    fertilising: 'Every 6–8 weeks spring/summer with high-phosphorus fertiliser to encourage blooming.',
    seasonal: 'Melbourne: flowers more in spring/summer with longer days. In winter reduce watering and stop fertilising. Keep above 16°C.',
    commonProblems: 'No flowers: insufficient light or needs phosphorus. Yellow leaves: overwatering. Brown tips: low humidity or fluoride in water.',
  },
  {
    id: 'anthurium-crystallinum',
    name: 'Anthurium Crystallinum',
    aliases: ['Crystal Anthurium', 'Velvet Anthurium'],
    emoji: '💎',
    baseIntervalDays: 7,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Crystal veins show best in good but filtered light.',
    watering: 'Keep consistently moist but never soggy. Use a well-draining orchid-type mix.',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser. Calcium helps vein development.',
    seasonal: 'Melbourne: needs warmth and high humidity year-round. A challenging but rewarding plant. Never below 15°C.',
    commonProblems: 'Yellowing: overwatering or low humidity. Dull veins: insufficient light. Brown patches: direct sun. Slow growth: needs higher humidity — use a humidifier.',
  },
  {
    id: 'syngonium',
    name: 'Arrowhead Vine',
    aliases: ['Syngonium podophyllum', 'Nephthytis', 'Goosefoot Plant'],
    emoji: '🏹',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Medium to bright indirect light. Variegated varieties need more light.',
    watering: 'Water when top 2–3cm is dry. Very forgiving — bounces back from neglect.',
    fertilising: 'Monthly spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: grows fast spring/summer. Prone to getting leggy in winter — trim and propagate.',
    commonProblems: 'Yellowing: overwatering. Leggy stems: insufficient light — needs more light or pinching back. Leaves reverting to green: insufficient light for variegated types.',
  },

  // ─── Peace Lily & Spathiphyllum already above ─────────────────────────────

  // ─── Succulents ──────────────────────────────────────────────────────────
  {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    aliases: ['Aloe barbadensis', 'True Aloe', 'Medicinal Aloe'],
    emoji: '🌵',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Bright indirect to direct sun. 4–6 hours of sun daily keeps it healthy.',
    watering: 'Water deeply when soil is completely dry. The gel-filled leaves store water — overwatering causes rot before underwatering does.',
    fertilising: 'Once in spring only with diluted succulent fertiliser. Rarely needs feeding.',
    seasonal: 'Melbourne: thrives outdoors on a sunny balcony in summer. Bring inside in winter. Barely water in winter (once per month).',
    commonProblems: 'Mushy brown base: overwatered/root rot — repot in dry succulent mix. Wrinkled thin leaves: severely underwatered — soak pot. Browning tips: too much direct afternoon sun or fluoride in water.',
  },
  {
    id: 'jade-plant',
    name: 'Jade Plant',
    aliases: ['Crassula ovata', 'Money Plant', 'Lucky Plant', 'Friendship Tree'],
    emoji: '💰',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Bright light — 4 hours of direct or very bright indirect sun daily.',
    watering: 'Water when soil is completely dry. The thick succulent leaves store water for weeks. In winter barely water (once per 3–4 weeks).',
    fertilising: 'Once in spring with balanced fertiliser. Can survive years without feeding.',
    seasonal: 'Melbourne: loves a sunny windowsill year-round. Can summer outside. Goes semi-dormant in winter — reduce watering dramatically. Very long-lived (20+ years).',
    commonProblems: 'Dropping leaves: overwatering or sudden temperature change. Wrinkled/shrivelled leaves: thirsty — water deeply. Leggy growth: insufficient light.',
  },
  {
    id: 'echeveria-elegans',
    name: 'Echeveria Elegans',
    aliases: ['Mexican Snowball', 'White Echeveria', 'Pearl Echeveria'],
    emoji: '🌸',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun to bright indirect light — at least 4–6 hours. Inadequate light causes etiolation (stretching).',
    watering: 'Water thoroughly when soil is completely dry. Water at the soil level — water on the rosette causes rot.',
    fertilising: 'Once in spring with very diluted succulent fertiliser.',
    seasonal: 'Melbourne: perfect for a sunny outdoor pot or rockery. Bring inside in winter if frost threatened. Barely water in winter.',
    commonProblems: 'Stretched/leggy rosette: insufficient light — place outdoors or in full sun window. Rotting centre: water sitting on leaves. Mushy base: root rot from overwatering.',
  },
  {
    id: 'echeveria-perle-von-nurnberg',
    name: 'Echeveria Perle von Nürnberg',
    aliases: ['PVN Echeveria', 'Pearl of Nurnberg'],
    emoji: '💜',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun preferred to maintain the purple/pink colouration. Low light turns leaves green.',
    watering: 'Deep watering when soil is completely dry. Never mist — water droplets mark the powdery coating.',
    fertilising: 'Once in spring, half-strength succulent fertiliser.',
    seasonal: 'Melbourne: outdoor plant in summer. The colour is most vivid with some stress (bright light, slight drought). Winter dormancy — minimal water.',
    commonProblems: 'Green leaves: insufficient light — move to sun. Marks on leaves: touching or water droplets damage the farina (powder coating). Stretching: etiolation from low light.',
  },
  {
    id: 'haworthia-fasciata',
    name: 'Haworthia Fasciata',
    aliases: ['Zebra Plant Haworthia', 'Zebra Cactus'],
    emoji: '🦓',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Bright indirect light. Tolerates lower light better than most succulents. Avoid direct harsh sun.',
    watering: 'Water when soil is completely dry. Very drought tolerant — perfect for forgetful waterers.',
    fertilising: 'Once in spring with diluted succulent fertiliser.',
    seasonal: 'Melbourne: excellent indoor succulent — tolerates the low light of Melbourne winters. Water only once per month in winter.',
    commonProblems: 'Orange/red tint to leaves: sun stress (harmless) or underwatering. Soft mushy leaves: overwatering. Very slow growth: completely normal for this species.',
  },
  {
    id: 'sedum-burros-tail',
    name: "Burro's Tail",
    aliases: ['Sedum morganianum', "Donkey's Tail", 'Burros Tail Sedum'],
    emoji: '🌾',
    baseIntervalDays: 14,
    difficulty: 'Intermediate',
    humidity: 'Low',
    toxic: false,
    light: 'Bright indirect light or gentle morning direct sun. At least 4 hours of light.',
    watering: 'Water when soil is completely dry. The trailing stems are extremely fragile — handle as little as possible.',
    fertilising: 'Once in spring with diluted succulent fertiliser.',
    seasonal: 'Melbourne: keep indoors in a bright spot year-round. Don\'t move it once established — stems drop at the slightest touch. Winter: once per month watering.',
    commonProblems: 'Falling leaves: touch, movement, or overwatering — find a permanent spot and leave it there. Flat/thin beads: underwatered. Mushy beads: overwatered.',
  },
  {
    id: 'hens-and-chicks',
    name: 'Hens and Chicks',
    aliases: ['Sempervivum', 'Houseleek', 'Live Forever'],
    emoji: '🌺',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun — at least 6 hours. Ideal outdoor plant.',
    watering: 'Very drought tolerant — water when soil is completely dry. Outdoor plants often survive on rainfall alone.',
    fertilising: 'Once per year in spring with diluted fertiliser. Over-feeding causes loose, floppy rosettes.',
    seasonal: 'Melbourne: perfect outdoor rock garden plant. Frost-hardy (to -15°C). After the main rosette flowers and dies, the "chicks" (offsets) replace it — this is normal.',
    commonProblems: 'Dying rosette: it has flowered — this is monocarpic (normal). Stretching: insufficient light. Root rot: overwatering or poor drainage.',
  },
  {
    id: 'gasteria',
    name: 'Gasteria',
    aliases: ['Ox Tongue Plant', 'Lawyer\'s Tongue'],
    emoji: '👅',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Tolerates low to medium indirect light. One of the most shade-tolerant succulents.',
    watering: 'Water when soil is completely dry. More tolerant of overwatering than Haworthia.',
    fertilising: 'Once in spring with diluted succulent fertiliser.',
    seasonal: 'Melbourne: an ideal indoor succulent for darker rooms. Water once per month in winter. Produces orange tubular flowers in spring.',
    commonProblems: 'Pale/washed out: too much direct sun. Soft leaves: overwatered. Very slow: completely normal — this is a slow-growing species.',
  },
  {
    id: 'lithops',
    name: 'Lithops',
    aliases: ['Living Stones', 'Pebble Plants', 'Split Rock'],
    emoji: '🪨',
    baseIntervalDays: 21,
    difficulty: 'Advanced',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun — 4–5 hours of direct sun essential.',
    watering: 'Extremely drought-tolerant. Water sparingly in autumn only (when soil is bone dry). Do NOT water at all Nov–March (active growth/shedding period). Resume watering in April–May.',
    fertilising: 'Never fertilise — any nutrient excess causes abnormal growth.',
    seasonal: 'Melbourne (reversed seasons): Water Aug–Nov (autumn/early winter). Completely stop Nov–March when they shed outer skin and grow new body. Melbourne\'s summer is their dry season.',
    commonProblems: 'Rotting: overwatering (the most common killer). Wrinkled and shrivelled body: watered at wrong time — wait for shedding to complete. Not flowering: needs full sun.',
  },

  // ─── Cacti ────────────────────────────────────────────────────────────────
  {
    id: 'golden-barrel-cactus',
    name: 'Golden Barrel Cactus',
    aliases: ['Echinocactus grusonii', "Mother-in-Law's Chair"],
    emoji: '🟡',
    baseIntervalDays: 21,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun — at least 6 hours of direct sun.',
    watering: 'Water thoroughly in spring/summer when soil is completely dry. Barely water in winter (once per 6–8 weeks).',
    fertilising: 'Once in spring with cactus fertiliser.',
    seasonal: 'Melbourne: excellent outdoor specimen plant in a sunny position. Tolerates heat well. Bring inside or cover if frost threatened.',
    commonProblems: 'Yellowing/softening: root rot from overwatering. Flattening/etiolation: insufficient light. Corking (brown at base): normal ageing.',
  },
  {
    id: 'christmas-cactus',
    name: 'Christmas Cactus',
    aliases: ['Schlumbergera', 'Holiday Cactus', 'Thanksgiving Cactus', 'Easter Cactus'],
    emoji: '🌺',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Avoid direct harsh sun.',
    watering: 'Water when top 2cm is dry — more than a typical cactus. Reduce to nearly dry in autumn to trigger blooming.',
    fertilising: 'Monthly spring/summer with high-phosphorus fertiliser to promote flowering.',
    seasonal: 'Melbourne: blooms around June–July (winter). Trigger blooming in April–May by reducing watering and moving to a cooler location (below 15°C nights). Resume normal care once buds form.',
    commonProblems: 'No blooms: didn\'t get cool, dry autumn rest period. Bud drop: moved or stressed while buds were forming. Limp segments: overwatered.',
  },
  {
    id: 'bunny-ear-cactus',
    name: 'Bunny Ear Cactus',
    aliases: ['Opuntia microdasys', 'Angel\'s Wings Cactus', 'Polka Dot Cactus'],
    emoji: '🐰',
    baseIntervalDays: 21,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun — loves a south or west-facing window.',
    watering: 'Water when completely dry in spring/summer. Barely water in winter.',
    fertilising: 'Once in spring with cactus fertiliser.',
    seasonal: 'Melbourne: great outdoor cactus for a dry sunny spot. Glochids (tiny spines) are extremely irritating — always use gloves.',
    commonProblems: 'Soft/yellow pads: overwatered — cut off affected pads. Shrivelling: underwatered. Glochid splinters in skin: use tweezers and tape to remove.',
  },
  {
    id: 'mammillaria',
    name: 'Mammillaria Cactus',
    aliases: ['Pincushion Cactus', 'Nipple Cactus'],
    emoji: '🌵',
    baseIntervalDays: 18,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Bright direct sun — south or west-facing window.',
    watering: 'Water when completely dry. A very drought-tolerant cactus. Winter: once per month.',
    fertilising: 'Once in spring with cactus fertiliser.',
    seasonal: 'Melbourne: produces a ring of beautiful small flowers in spring. A cool dry winter encourages flowering. Suitable for outdoor sunny spots.',
    commonProblems: 'No flowers: needs cooler, drier winter. Root rot: overwatering. White fluffy patches: mealy bugs — treat with isopropyl alcohol on cotton swab.',
  },

  // ─── Fiddle Leaf Fig & Tropicals ─────────────────────────────────────────
  {
    id: 'fiddle-leaf-fig',
    name: 'Fiddle Leaf Fig',
    aliases: ['Ficus lyrata', 'FLF'],
    emoji: '🎸',
    baseIntervalDays: 7,
    difficulty: 'Advanced',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light — near a window but not in direct harsh sun. Consistent light is key (do not move the plant once settled).',
    watering: 'Water when top 3–4cm is dry. Dramatic drooper when thirsty. Hates wet feet — ensure drainage is perfect.',
    fertilising: 'Monthly spring/summer with high-nitrogen fertiliser. Essential for large healthy leaves.',
    seasonal: 'Melbourne: find its happy spot and leave it there permanently. Dislikes moving and will drop leaves in protest. Reduce watering in winter. Clean leaves monthly to maximise photosynthesis.',
    commonProblems: 'Leaf drop: moved the plant, cold draft, or overwatering. Brown spots: underwatering, root rot, or bacterial infection. Yellowing: overwatering. New leaves unfurling damaged: low humidity or physical contact.',
  },
  {
    id: 'rubber-plant',
    name: 'Rubber Plant',
    aliases: ['Ficus elastica', 'Indian Rubber Tree'],
    emoji: '🌿',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. More tolerant of lower light than Fiddle Leaf Fig. Variegated varieties need more light.',
    watering: 'Water when top 3–4cm is dry. Much more forgiving than its cousin the FLF.',
    fertilising: 'Monthly spring/summer with balanced liquid fertiliser.',
    seasonal: 'Melbourne: grows fast in warm months. Clean leaves regularly — large leaves collect dust. Winter: every 14 days. Wipe milky sap from hands after handling.',
    commonProblems: 'Dropping lower leaves: overwatering, cold draft, or low light. Yellow leaves: overwatering. Dusty leaves: wipe monthly with damp cloth.',
  },
  {
    id: 'weeping-fig',
    name: 'Weeping Fig',
    aliases: ['Ficus benjamina', 'Benjamina Fig'],
    emoji: '🌳',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Tolerates medium light.',
    watering: 'Keep consistently moist — water when top 2cm is dry.',
    fertilising: 'Monthly spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: notorious leaf dropper when moved or stressed. Find a permanent spot. Reduce watering in winter.',
    commonProblems: 'Leaf drop: moving the plant, drafts, low light, or overwatering. Yellow leaves: overwatering. This is one of the fussiest houseplants — consistency is everything.',
  },
  {
    id: 'ficus-audrey',
    name: 'Ficus Audrey',
    aliases: ['Ficus benghalensis', 'Banyan Tree', 'Bengal Fig'],
    emoji: '🌿',
    baseIntervalDays: 10,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Much more forgiving than Fiddle Leaf Fig.',
    watering: 'Water when top 3–4cm is dry.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: the more forgiving Ficus alternative. Less likely to drop leaves when moved. Grows vigorously spring/summer.',
    commonProblems: 'Yellowing: overwatering. Leaf drop: less common than FLF but still possible with cold drafts. Generally easier than other Ficus varieties.',
  },
  {
    id: 'bird-of-paradise',
    name: 'Bird of Paradise',
    aliases: ['Strelitzia reginae', 'Crane Flower', 'Strelitzia nicolai (Giant)'],
    emoji: '🦜',
    baseIntervalDays: 10,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright direct to bright indirect light. Needs maximum light to flower.',
    watering: 'Water when top 3–4cm is dry. Drought tolerant once established.',
    fertilising: 'Monthly spring/summer with balanced liquid fertiliser. Needs consistent feeding to produce flowers.',
    seasonal: 'Melbourne: grows beautifully outdoors in a sunny sheltered spot. Flowers in spring after a cool winter. Indoor plants rarely flower without full sun. Frost-tolerant to -2°C.',
    commonProblems: 'No flowers: insufficient light or too young (can take 3–5 years from seed). Split leaves: normal — outdoor wind splits them naturally. Yellowing: overwatering.',
  },
  {
    id: 'banana-plant',
    name: 'Banana Plant',
    aliases: ['Musa', 'Ensete', 'Ornamental Banana'],
    emoji: '🍌',
    baseIntervalDays: 5,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Full sun to bright indirect light. Needs maximum light for large leaves.',
    watering: 'Keep consistently moist — water when top 2–3cm is dry. Thirsty in summer. Reduce in winter.',
    fertilising: 'Every 2–3 weeks spring/summer with high-nitrogen fertiliser. Big feeders.',
    seasonal: 'Melbourne: thrives outdoors in a sheltered sunny spot in summer. Protect from strong winds (splits leaves). Most varieties won\'t fruit indoors. Cut back and mulch over winter.',
    commonProblems: 'Split leaves: wind damage (normal outdoors). Yellowing lower leaves: natural ageing. Brown crispy edges: low humidity or underwatering.',
  },

  // ─── Calathea & Prayer Plants ─────────────────────────────────────────────
  {
    id: 'calathea-ornata',
    name: 'Calathea Ornata',
    aliases: ['Pinstripe Plant', 'Ornata Calathea'],
    emoji: '📌',
    baseIntervalDays: 5,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: false,
    light: 'Medium to bright indirect light. Avoid direct sun — scorches the decorative markings.',
    watering: 'Keep consistently moist. Use filtered or distilled water — extremely sensitive to fluoride and minerals.',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: needs a humidifier in dry conditions. Opens and closes leaves with day/night cycle (prayer movement). Requires high humidity year-round — difficult in dry Melbourne winters.',
    commonProblems: 'Brown crispy edges: low humidity or mineral-rich tap water. Curling leaves: underwatered or low humidity. Yellowing: overwatering. Drooping: underwatered. Extremely sensitive to tap water chlorine/fluoride.',
  },
  {
    id: 'calathea-medallion',
    name: 'Calathea Medallion',
    aliases: ['Calathea veitchiana', 'Medallion Prayer Plant'],
    emoji: '🥇',
    baseIntervalDays: 5,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: false,
    light: 'Medium indirect light. A relatively more tolerant Calathea variety.',
    watering: 'Keep consistently moist with filtered or rainwater. Never let it dry out completely.',
    fertilising: 'Monthly spring/summer. Less is more.',
    seasonal: 'Melbourne: group with other tropicals to create a humid microclimate. Humidifier essential in winter. Close proximity to air conditioning will damage leaves.',
    commonProblems: 'Brown tips and edges: low humidity, fluoride in water, or drafts from AC. Yellowing: overwatering. Faded pattern: insufficient light.',
  },
  {
    id: 'calathea-zebrina',
    name: 'Calathea Zebrina',
    aliases: ['Zebra Plant Calathea', 'Zebra Calathea'],
    emoji: '🦓',
    baseIntervalDays: 5,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: false,
    light: 'Medium to bright indirect light to maintain the vivid zebra pattern.',
    watering: 'Consistently moist with filtered/rainwater. Sensitive to minerals and fluoride in tap water.',
    fertilising: 'Monthly spring/summer, diluted.',
    seasonal: 'Melbourne: challenges in winter due to dry heated air. Use a humidifier or group with other plants. Avoid cold windowsills.',
    commonProblems: 'Crispy brown edges: low humidity (most common issue). Yellowing: overwatering. Faded stripes: needs more indirect light.',
  },
  {
    id: 'calathea-musaica',
    name: 'Calathea Musaica',
    aliases: ['Network Plant', 'Goeppertia kegeljanii', 'Calathea Network'],
    emoji: '🔲',
    baseIntervalDays: 5,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Bright indirect light — the mosaic pattern is most vivid with good light.',
    watering: 'Consistently moist with filtered water. Slightly more tolerant than other Calatheas.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: a slightly easier Calathea. Still needs humidity but handles lower light better than zebrina.',
    commonProblems: 'Brown tips: low humidity. Yellowing: overwatering. Faded network pattern: needs more indirect light.',
  },
  {
    id: 'maranta-prayer-plant',
    name: 'Prayer Plant',
    aliases: ['Maranta leuconeura', 'Red Prayer Plant', 'Herringbone Plant'],
    emoji: '🙏',
    baseIntervalDays: 5,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Medium to bright indirect light. Tolerates lower light than Calatheas.',
    watering: 'Keep consistently moist using filtered water. Folds leaves up at night (prayer movement).',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: easier than Calatheas but still needs humidity. Group with other plants. Reduce watering in winter.',
    commonProblems: 'Brown crispy edges: low humidity or tap water fluoride. Leaves not moving: insufficient light. Yellowing: overwatering.',
  },
  {
    id: 'stromanthe-triostar',
    name: 'Stromanthe Triostar',
    aliases: ['Triostar Stromanthe', 'Tricolor Stromanthe', 'Stromanthe sanguinea'],
    emoji: '🌈',
    baseIntervalDays: 5,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: false,
    light: 'Bright indirect light to maintain the pink/white/green variegation.',
    watering: 'Consistently moist with filtered or rainwater. Never let dry out.',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: the most demanding of the prayer plant family. Needs high humidity constantly — a humidifier is essential. The pink backs of leaves are stunning.',
    commonProblems: 'Brown crispy edges: low humidity. Reverting to green: insufficient light. Yellowing: overwatering or cold.',
  },

  // ─── Dracaena ─────────────────────────────────────────────────────────────
  {
    id: 'dracaena-marginata',
    name: 'Dracaena Marginata',
    aliases: ['Dragon Tree', 'Madagascar Dragon Tree', 'Dracaena marginata'],
    emoji: '🐉',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Medium to bright indirect light. Tolerates lower light well.',
    watering: 'Water when top half of soil is dry. Sensitive to fluoride — use filtered water.',
    fertilising: 'Monthly spring/summer with low-fluoride fertiliser.',
    seasonal: 'Melbourne: excellent low-maintenance indoor tree. Reduce to every 14–18 days in winter. Remove lower leaves as they yellow — this is natural ageing.',
    commonProblems: 'Brown tips: fluoride in tap water or low humidity — switch to rainwater. Yellow lower leaves: natural ageing (normal). Root rot: overwatering.',
  },
  {
    id: 'dracaena-corn-plant',
    name: 'Corn Plant',
    aliases: ['Dracaena fragrans', 'Happy Plant', 'Dracaena deremensis'],
    emoji: '🌽',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Low to bright indirect light. One of the most shade-tolerant houseplants.',
    watering: 'Water when top half is dry. Very drought tolerant.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: great for offices or rooms with little natural light. Reduce to every 14–18 days in winter.',
    commonProblems: 'Brown tips: fluoride from tap water. Yellow lower leaves: normal ageing. Root rot from overwatering is the main risk.',
  },

  // ─── Snake Plants ─────────────────────────────────────────────────────────
  {
    id: 'snake-plant-laurentii',
    name: 'Snake Plant',
    aliases: ['Sansevieria laurentii', 'Dracaena trifasciata', "Mother-in-Law's Tongue", 'Viper\'s Bowstring'],
    emoji: '🗡️',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'both',
    light: 'Tolerates almost any light — from very low to bright indirect. Direct sun possible but causes yellowing.',
    watering: 'Water when soil is completely dry. One of the most drought-tolerant houseplants. In winter, water as rarely as once per month.',
    fertilising: 'Once in spring and once in summer with balanced fertiliser. Barely needs feeding.',
    seasonal: 'Melbourne: the ultimate low-maintenance plant. Thrives on neglect. Reduce to monthly watering in winter. Can survive for 6 weeks without water.',
    commonProblems: 'Mushy base: root rot from overwatering — the only real way to kill this plant. Yellow leaves: overwatering or direct sun. Falling over: very underwatered or root-bound.',
  },
  {
    id: 'snake-plant-moonshine',
    name: 'Moonshine Snake Plant',
    aliases: ['Dracaena trifasciata Moonshine', 'Silver Snake Plant', 'Sansevieria moonshine'],
    emoji: '🌙',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'both',
    light: 'Medium to bright indirect light keeps the silvery-green colour vivid. Very low light dulls colouring.',
    watering: 'Same as standard snake plant — water when completely dry.',
    fertilising: 'Once in spring with balanced fertiliser.',
    seasonal: 'Melbourne: same care as standard snake plant. The pale silvery colour is most pronounced in good light.',
    commonProblems: 'Colour fading to dark green: insufficient light. Root rot: overwatering. Otherwise as resilient as standard snake plant.',
  },
  {
    id: 'snake-plant-cylindrica',
    name: 'Cylindrical Snake Plant',
    aliases: ['Sansevieria cylindrica', 'African Spear', 'Spear Sansevieria'],
    emoji: '🎯',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light preferred but tolerates low light.',
    watering: 'Water when completely dry. Handles neglect as well as standard snake plant.',
    fertilising: 'Once in spring only.',
    seasonal: 'Melbourne: same care as standard snake plant. Very drought tolerant.',
    commonProblems: 'Root rot: the only real risk from overwatering. Wrinkled cylindrical leaves: severely underwatered — soak pot.',
  },

  // ─── ZZ Plant & Others ────────────────────────────────────────────────────
  {
    id: 'zz-plant',
    name: 'ZZ Plant',
    aliases: ['Zamioculcas zamiifolia', 'Zanzibar Gem', 'Zz Zenzi'],
    emoji: '💎',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'both',
    light: 'Extremely shade tolerant — survives in very low light. Bright indirect light for faster growth.',
    watering: 'Water when soil is completely dry. Rhizomes store water — extremely drought tolerant. Easier to kill with overwatering than underwatering.',
    fertilising: 'Once in spring with balanced fertiliser.',
    seasonal: 'Melbourne: one of the best plants for dark indoor spaces. Water once per month in winter. Nearly indestructible.',
    commonProblems: 'Yellow leaves: overwatering or root rot. Stunted growth: too dark. Wash hands after handling — mild toxicity.',
  },
  {
    id: 'cast-iron-plant',
    name: 'Cast Iron Plant',
    aliases: ['Aspidistra elatior', 'Bar Room Plant'],
    emoji: '🔩',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Deep shade to low indirect light. Lives up to its name — virtually indestructible.',
    watering: 'Water when top half is dry. Very drought tolerant.',
    fertilising: 'Once in spring. Minimal feeder.',
    seasonal: 'Melbourne: ideal for very dark rooms or shaded outdoor areas. Can survive outdoors in Melbourne year-round in a sheltered position.',
    commonProblems: 'Yellow leaves: overwatering. Spotted/striped leaves: normal — variegated varieties. Slow growth: completely normal — this is a very slow grower.',
  },

  // ─── Ferns ────────────────────────────────────────────────────────────────
  {
    id: 'boston-fern',
    name: 'Boston Fern',
    aliases: ['Nephrolepis exaltata', 'Sword Fern'],
    emoji: '🌿',
    baseIntervalDays: 3,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Bright indirect light. Avoid direct sun.',
    watering: 'Keep consistently moist — water when top 1cm is dry. Never let it dry out completely.',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: loves Melbourne\'s humid summers. Needs daily misting or a pebble tray in dry conditions. In winter, reduce watering slightly but maintain humidity.',
    commonProblems: 'Yellowing and dropping fronds: low humidity, underwatering, or overwatering. Brown fronds: low humidity — mist daily. Shedding: normal when moved or stressed.',
  },
  {
    id: 'maidenhair-fern',
    name: 'Maidenhair Fern',
    aliases: ['Adiantum', 'Delta Maidenhair'],
    emoji: '🌱',
    baseIntervalDays: 2,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: false,
    light: 'Bright indirect light. Avoid direct sun and cold drafts.',
    watering: 'Keep consistently moist — water daily if in a dry environment. Extremely sensitive to drying out (collapses immediately).',
    fertilising: 'Monthly spring/summer at quarter strength.',
    seasonal: 'Melbourne: one of the most challenging houseplants. Needs constant high humidity. Best kept in a bathroom with natural light or in a glass cabinet. If it collapses, cut all fronds and water thoroughly — it may regrow from the rhizome.',
    commonProblems: 'Sudden complete collapse: dried out (most common). Fronds turning brown: low humidity. Root rot: overwatering without good drainage. Recovery tip: cut back completely and re-water — often regrows.',
  },
  {
    id: 'birds-nest-fern',
    name: "Bird's Nest Fern",
    aliases: ['Asplenium nidus', 'Nest Fern'],
    emoji: '🪺',
    baseIntervalDays: 5,
    difficulty: 'Beginner',
    humidity: 'High',
    toxic: false,
    light: 'Low to medium indirect light. A very adaptable fern.',
    watering: 'Keep consistently moist. Water around the outer soil, never into the centre rosette — this causes rot.',
    fertilising: 'Monthly spring/summer with diluted balanced fertiliser.',
    seasonal: 'Melbourne: one of the easier ferns. Tolerates Melbourne\'s variable conditions better than Maidenhair. Loves bathroom humidity.',
    commonProblems: 'Yellowing: overwatering. Brown crispy edges: low humidity or direct sun. Rotting centre: water getting into the central crown.',
  },
  {
    id: 'staghorn-fern',
    name: 'Staghorn Fern',
    aliases: ['Platycerium bifurcatum', 'Elkhorn Fern'],
    emoji: '🦌',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Bright indirect light. Can tolerate some morning direct sun.',
    watering: 'Soak the shield fronds or dunk the whole plant in water for 20 minutes. Allow to dry before next watering. The brown papery shield fronds must not be removed — they protect the root ball.',
    fertilising: 'Monthly spring/summer — apply fertiliser to the shield frond, not the antler frond.',
    seasonal: 'Melbourne: beautiful mounted on a piece of timber. Grows on Melbourne\'s verandahs and outdoor walls happily in sheltered spots. Water more frequently in summer.',
    commonProblems: 'Black rotting shield fronds: overwatered. Brown/drooping antler fronds: underwatered. Do not remove shield fronds — even black ones are normal.',
  },

  // ─── Palms ────────────────────────────────────────────────────────────────
  {
    id: 'kentia-palm',
    name: 'Kentia Palm',
    aliases: ['Howea forsteriana', 'Thatch Palm', 'Sentry Palm'],
    emoji: '🌴',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Low to bright indirect light. One of the most shade-tolerant palms.',
    watering: 'Water when top 3–4cm is dry. Very drought tolerant once established.',
    fertilising: 'Monthly spring/summer with palm fertiliser (contains micronutrients).',
    seasonal: 'Melbourne: a slow-growing architectural plant. Thrives in Melbourne homes. Native to Lord Howe Island — adapted to the Australian climate. Reduce watering in winter.',
    commonProblems: 'Brown tips: fluoride in water or low humidity — use rainwater. Yellow fronds: overwatering or lack of micronutrients. Slow growth: completely normal for Kentia.',
  },
  {
    id: 'parlour-palm',
    name: 'Parlour Palm',
    aliases: ['Chamaedorea elegans', 'Neanthe Bella Palm'],
    emoji: '🌿',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Low to medium indirect light. An excellent palm for darker rooms.',
    watering: 'Water when top 2–3cm is dry. Sensitive to overwatering.',
    fertilising: 'Monthly spring/summer with palm fertiliser.',
    seasonal: 'Melbourne: ideal indoor palm for any room. Slow grower. Reduce watering in winter.',
    commonProblems: 'Brown tips: low humidity or overwatering. Yellow fronds: overwatering. Spider mites: common — inspect regularly and mist leaves.',
  },
  {
    id: 'areca-palm',
    name: 'Areca Palm',
    aliases: ['Dypsis lutescens', 'Butterfly Palm', 'Golden Cane Palm'],
    emoji: '🌴',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. One of the fastest-growing indoor palms.',
    watering: 'Keep slightly moist — water when top 2–3cm is dry. Sensitive to fluoride.',
    fertilising: 'Monthly spring/summer with palm fertiliser.',
    seasonal: 'Melbourne: grows into a large statement plant. Use rainwater to avoid brown tips. Reduce watering in winter.',
    commonProblems: 'Brown tips: fluoride in water or salt build-up. Yellowing fronds: overwatering. Spider mites: common — treat with neem oil.',
  },

  // ─── Spider Plant & Others ────────────────────────────────────────────────
  {
    id: 'spider-plant',
    name: 'Spider Plant',
    aliases: ['Chlorophytum comosum', 'Airplane Plant', "Hen and Chickens"],
    emoji: '🕷️',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Medium to bright indirect light. Very adaptable.',
    watering: 'Water when top 3cm is dry. Extremely forgiving.',
    fertilising: 'Monthly spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: produces long arching stems with "spiderettes" (baby plants) in spring/summer. Cut and propagate babies in water. Reduces watering in winter.',
    commonProblems: 'Brown tips: fluoride in tap water, over-fertilising, or low humidity. Yellow stripes: too little light for variegated varieties. Root bound: actually blooms more when slightly root bound.',
  },
  {
    id: 'ponytail-palm',
    name: 'Ponytail Palm',
    aliases: ['Beaucarnea recurvata', 'Elephant Foot Tree', 'Bottle Palm'],
    emoji: '🐴',
    baseIntervalDays: 21,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Bright light — as much direct sun as possible.',
    watering: 'Water deeply when soil is completely dry. The swollen base stores water — very drought tolerant.',
    fertilising: 'Once in spring with balanced fertiliser.',
    seasonal: 'Melbourne: extremely drought-tolerant. Ideal for a sunny window or outdoor position. Barely water in winter (once per month or less).',
    commonProblems: 'Root rot: overwatering. Splitting base: extreme underwatering. Brown crispy leaf tips: normal due to leaf age. Very slow growing.',
  },
  {
    id: 'money-tree',
    name: 'Money Tree',
    aliases: ['Pachira aquatica', 'Guiana Chestnut', 'Malabar Chestnut'],
    emoji: '🌳',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Tolerates some direct morning sun.',
    watering: 'Water when top half of soil is dry. Drought tolerant. Don\'t overwater — root rot is the main risk.',
    fertilising: 'Monthly spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: a popular Feng Shui plant. Reduce watering in winter. The braided trunk is created when young — it won\'t braid further once woody.',
    commonProblems: 'Yellow leaves: overwatering or low light. Dropping leaves: drafts or sudden temperature change. Rotting base: root rot from overwatering.',
  },
  {
    id: 'umbrella-plant',
    name: 'Umbrella Plant',
    aliases: ['Schefflera actinophylla', 'Queensland Umbrella Tree', 'Octopus Tree'],
    emoji: '☂️',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Medium to bright indirect light.',
    watering: 'Water when top 3cm is dry. Tolerates occasional drought.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: fast-growing, can get large. Prune in spring to keep bushy. Reduce watering in winter.',
    commonProblems: 'Dropping leaves: overwatering, low light, or drafts. Yellow leaves: overwatering. Leggy: needs more light.',
  },
  {
    id: 'english-ivy',
    name: 'English Ivy',
    aliases: ['Hedera helix', 'Common Ivy'],
    emoji: '🌿',
    baseIntervalDays: 5,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Variegated varieties need more light.',
    watering: 'Keep consistently moist. Don\'t let dry out completely.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: can grow outdoors in Melbourne year-round. As a houseplant prefers cooler temperatures. Susceptible to spider mites in warm/dry conditions.',
    commonProblems: 'Spider mites: very common in dry warm conditions — mist regularly and check undersides of leaves. Yellowing: overwatering. Leggy: insufficient light.',
  },
  {
    id: 'chinese-money-plant',
    name: 'Chinese Money Plant',
    aliases: ['Pilea peperomioides', 'Pancake Plant', 'UFO Plant'],
    emoji: '🪙',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Rotate regularly for even growth — leans towards light.',
    watering: 'Water when top 2–3cm is dry. Leaves cup upwards when thirsty.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: popular and easy. Produces many "pups" (offsets) at the base — propagate freely. Reduce watering in winter.',
    commonProblems: 'Leaning: rotate pot quarterly. Drooping leaves: thirsty — water immediately. Yellow leaves: overwatering. Curling leaves: too much direct sun.',
  },
  {
    id: 'oxalis',
    name: 'Oxalis',
    aliases: ['Wood Sorrel', 'Shamrock Plant', 'Purple Oxalis', 'Love Plant'],
    emoji: '🍀',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Bright indirect to some direct sun. Leaves open and close with light.',
    watering: 'Water when top 2cm is dry. Allow to go dry and dormant in summer (Melbourne) — this is normal.',
    fertilising: 'Monthly during active growth.',
    seasonal: 'Melbourne: Oxalis triangularis grows actively in Melbourne\'s autumn/winter. Goes dormant in summer — leave bulbs in the pot and they regrow in autumn. Don\'t discard!',
    commonProblems: 'Complete die-back: summer dormancy — normal! New growth returns in autumn. Yellowing: overwatering during active growth. Leggy: insufficient light.',
  },

  // ─── Peperomias ──────────────────────────────────────────────────────────
  {
    id: 'peperomia-obtusifolia',
    name: 'Baby Rubber Plant',
    aliases: ['Peperomia obtusifolia', 'American Rubber Plant', 'Pepper Face'],
    emoji: '🌿',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Medium to bright indirect light.',
    watering: 'Water when top half is dry. Succulent leaves store water — very forgiving.',
    fertilising: 'Monthly spring/summer at half strength.',
    seasonal: 'Melbourne: extremely easy indoor plant. Reduce watering in winter. Compact and perfect for shelves.',
    commonProblems: 'Yellow mushy leaves: overwatering. Wilting: very underwatered or root rot. Black spots on leaves: cold damage.',
  },
  {
    id: 'peperomia-watermelon',
    name: 'Watermelon Peperomia',
    aliases: ['Peperomia argyreia', 'Watermelon Begonia'],
    emoji: '🍉',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light to maintain the watermelon stripe pattern.',
    watering: 'Water when top half of soil is dry. Semi-succulent petioles store water.',
    fertilising: 'Monthly spring/summer at half strength.',
    seasonal: 'Melbourne: popular easy-care indoor plant. Compact — great for desks and shelves. Reduces watering in winter.',
    commonProblems: 'Faded stripes: insufficient light. Mushy leaves: overwatered. Scab-like spots: edema from inconsistent watering.',
  },
  {
    id: 'peperomia-caperata',
    name: 'Ripple Peperomia',
    aliases: ['Peperomia caperata', 'Emerald Ripple'],
    emoji: '🌊',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. The rippled texture shows best with adequate light.',
    watering: 'Water when top half is dry. Very forgiving.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: produces tall flower spikes (rat tails) in spring — harmless, remove if unwanted.',
    commonProblems: 'Yellowing: overwatering. Dull leaves: needs more light. Limp leaves: severely underwatered.',
  },

  // ─── Herbs ────────────────────────────────────────────────────────────────
  {
    id: 'basil',
    name: 'Basil',
    aliases: ['Sweet Basil', 'Ocimum basilicum', 'Thai Basil'],
    emoji: '🌿',
    baseIntervalDays: 2,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: false,
    light: 'Full sun — at least 6 hours of direct sun essential. Best on a north-facing windowsill.',
    watering: 'Water daily or every other day in Melbourne\'s summer. Wilts dramatically when thirsty but recovers quickly. Water at the base, not on leaves.',
    fertilising: 'Every 2–3 weeks with balanced liquid fertiliser during growing season.',
    seasonal: 'Melbourne: grow outdoors Oct–Apr. Buy a fresh plant each spring. Pinch flower buds immediately — flowering makes leaves bitter. Goes to seed and dies in summer heat.',
    commonProblems: 'Wilting: underwatered (water immediately). Flowering: pinch out immediately to extend leaf harvest. Leggy: insufficient light. Yellow leaves: overwatering.',
  },
  {
    id: 'mint',
    name: 'Mint',
    aliases: ['Mentha', 'Spearmint', 'Peppermint', 'Moroccan Mint'],
    emoji: '🍃',
    baseIntervalDays: 2,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: true, toxicTo: 'pets',
    light: 'Medium to bright indirect light or morning direct sun.',
    watering: 'Keep consistently moist — mint is thirsty. Water every 1–2 days in summer.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: extremely vigorous grower in spring/summer — contains it in a pot or it will take over the garden. Goes dormant in winter. Cuts back to the ground and regrows in spring.',
    commonProblems: 'Spread: pot it in a container always. Rust fungus (orange powder on leaves): remove affected leaves, improve air circulation. Wilting: very thirsty — water immediately.',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    aliases: ['Salvia rosmarinus', 'Rosmarinus officinalis'],
    emoji: '🌿',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun — 6+ hours of direct sun. Mediterranean plant.',
    watering: 'Water when top half of soil is dry. Drought tolerant once established. Overwatering is the main killer.',
    fertilising: 'Twice per year (spring and summer) with balanced fertiliser.',
    seasonal: 'Melbourne: perfect outdoor herb for Melbourne\'s climate. Thrives in well-drained soil. Cut back after flowering. Very long-lived if not overwatered.',
    commonProblems: 'Root rot/sudden death: overwatering or poor drainage. Powdery mildew: poor airflow — grow outdoors. Woody bare stems: cut back by 1/3 in spring.',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    aliases: ['Thymus vulgaris', 'Common Thyme', 'Garden Thyme'],
    emoji: '🌱',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Full sun — minimum 4–6 hours of direct sun.',
    watering: 'Water when top half of soil is dry. Drought tolerant. Good drainage essential.',
    fertilising: 'Once in spring. Over-fertilising reduces flavour.',
    seasonal: 'Melbourne: excellent outdoor herb. Woody perennial — cut back by half in spring to encourage new growth. Very heat tolerant in Melbourne summers.',
    commonProblems: 'Root rot: poor drainage. Woody/bare growth: cut back in spring. Spider mites in hot dry conditions: mist undersides of leaves.',
  },
  {
    id: 'coriander',
    name: 'Coriander',
    aliases: ['Cilantro', 'Coriandrum sativum', 'Chinese Parsley'],
    emoji: '🌿',
    baseIntervalDays: 2,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light or morning sun. Prefers cooler temperatures.',
    watering: 'Keep consistently moist. Bolts (flowers and goes to seed) quickly in heat.',
    fertilising: 'Monthly during active growth.',
    seasonal: 'Melbourne: best grown autumn through spring (cool season herb). Bolts in summer heat. Sow new seeds every 4 weeks for continuous harvest. Harvest outer leaves regularly to delay bolting.',
    commonProblems: 'Bolting (going to seed): summer heat or heat from a window. Yellowing: overwatering. Slow or no growth: insufficient light.',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    aliases: ['Petroselinum crispum', 'Flat-leaf Parsley', 'Curly Parsley'],
    emoji: '🌿',
    baseIntervalDays: 3,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect to direct morning sun.',
    watering: 'Keep consistently moist. Don\'t let it dry out.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: biennial — best in its first year. Plant in autumn for winter harvest. Bolts in its second year. Easy from seed.',
    commonProblems: 'Slow to germinate: normal — takes 3–4 weeks. Bolting: second-year plant going to seed — replace. Yellowing: overwatering.',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    aliases: ['Lavandula', 'English Lavender', 'French Lavender'],
    emoji: '💜',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Full sun — 6+ hours of direct sun essential.',
    watering: 'Water when top half of soil is dry. Very drought tolerant. Must have excellent drainage.',
    fertilising: 'Once in spring.',
    seasonal: 'Melbourne: thrives outdoors in Melbourne\'s climate — plant in a sunny, well-drained position. Prune after flowering to prevent woodiness. French lavender blooms multiple times per year in Melbourne.',
    commonProblems: 'Root rot and death: overwatering or poor drainage. Woody bare stems: cut back in early autumn by 1/3. Not flowering: insufficient sun.',
  },

  // ─── Orchids ─────────────────────────────────────────────────────────────
  {
    id: 'phalaenopsis-orchid',
    name: 'Phalaenopsis Orchid',
    aliases: ['Moth Orchid', 'Phal', 'Butterfly Orchid'],
    emoji: '🌺',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Morning or late afternoon sun is OK. No harsh midday sun.',
    watering: 'Water weekly by running under a tap for 30 seconds, then let drain completely. Never sit in standing water — crown rot is fatal.',
    fertilising: '"Weekly weakly" — diluted balanced fertiliser (quarter strength) every watering in spring/summer. Skip in winter.',
    seasonal: 'Melbourne: blooms in winter/spring. After blooms drop, cut spike to a node to rebloom. Give a cooler night temperature in autumn (12–15°C) to trigger new spike. Reblooms once per year.',
    commonProblems: 'No reblooming: needs cooler nights in autumn (move near a window). Yellowing leaves: overwatering or root rot (check roots in clear pot — healthy = green/silver). Crown rot: water sitting in the crown.',
  },
  {
    id: 'dendrobium-orchid',
    name: 'Dendrobium Orchid',
    aliases: ['Den Orchid', 'Singapore Orchid'],
    emoji: '🌸',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. More tolerant of direct morning sun than Phalaenopsis.',
    watering: 'Water when bark mix is almost dry. Reduce watering significantly in winter (the cool dry rest period triggers spring blooming).',
    fertilising: 'Monthly spring/summer. Stop in winter.',
    seasonal: 'Melbourne: the cool winter rest period is important for flowering. Most Dendrobiums bloom profusely in spring after a dry, cool winter rest.',
    commonProblems: 'No blooms: didn\'t get a dry/cool winter rest. Yellowing pseudobulbs: losing lower bulbs is normal (old canes). Wrinkled canes: underwatered.',
  },

  // ─── Bromeliads ──────────────────────────────────────────────────────────
  {
    id: 'aechmea-bromeliad',
    name: 'Aechmea',
    aliases: ['Aechmea fasciata', 'Silver Vase', 'Urn Plant'],
    emoji: '🏺',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Tolerates lower light.',
    watering: 'Keep the central "cup" (vase) filled with water — top up weekly. Water the soil monthly. Empty and refill the cup monthly to prevent stagnation.',
    fertilising: 'Monthly spring/summer — add diluted fertiliser to the central cup.',
    seasonal: 'Melbourne: the main plant blooms once then dies, replaced by "pups" (offsets). Pups take 1–2 years to bloom. Easy outdoor plant in a sheltered spot in Melbourne.',
    commonProblems: 'Mother plant dying after bloom: completely normal — harvest the pups. Pups not growing: may need more light. Brown cup: water rotting in cup — flush and refill regularly.',
  },
  {
    id: 'tillandsia-air-plant',
    name: 'Air Plant',
    aliases: ['Tillandsia', 'Atmospheric Plant'],
    emoji: '💨',
    baseIntervalDays: 7,
    difficulty: 'Beginner',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light. Near a window but not in direct harsh sun.',
    watering: 'Submerge in water for 20–30 minutes once per week. Shake off excess water and allow to fully dry within 4 hours — sitting wet causes rot. Mist 2–3x per week as a supplement in dry Melbourne summer.',
    fertilising: 'Monthly during soak with air plant or bromeliad fertiliser.',
    seasonal: 'Melbourne: needs more frequent soaking in dry summers. In winter, soak every 10 days. After blooming, produces pups then dies — normal. Avoid copper near air plants (toxic).',
    commonProblems: 'Mushy brown base: didn\'t dry quickly enough after watering. Drying out and dying: insufficient watering. Not attaching to mount: use non-toxic glue or wire — never super glue or copper wire.',
  },
  {
    id: 'tillandsia-xerographica',
    name: 'Tillandsia Xerographica',
    aliases: ['Xero Air Plant', 'King of Air Plants'],
    emoji: '👑',
    baseIntervalDays: 14,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: false,
    light: 'Bright light — tolerates more direct sun than most Tillandsia.',
    watering: 'Soak for 1 hour every 1–2 weeks. Allow to dry fully (shake out water from the centre). More drought tolerant than other air plants.',
    fertilising: 'Monthly with diluted air plant fertiliser added to soak water.',
    seasonal: 'Melbourne: extremely drought tolerant. Can go 2–3 weeks without water. A statement plant — the large silver rosette is stunning.',
    commonProblems: 'Rotting centre: water pooling and not drying. Crispy brown leaf tips: too dry — increase soak frequency. Very slow growing: completely normal.',
  },
  {
    id: 'guzmania-bromeliad',
    name: 'Guzmania',
    aliases: ['Scarlet Star', 'Tufted Airplant', 'Guzmania lingulata'],
    emoji: '⭐',
    baseIntervalDays: 10,
    difficulty: 'Beginner',
    humidity: 'High',
    toxic: false,
    light: 'Medium to bright indirect light.',
    watering: 'Keep the central rosette cup filled with water. Change the water monthly to prevent stagnation.',
    fertilising: 'Monthly spring/summer — add diluted fertiliser to the cup.',
    seasonal: 'Melbourne: vibrant red/orange/yellow bracts last for months. After the bloom the mother plant dies and is replaced by pups — harvest when 1/3 the size of the mother.',
    commonProblems: 'Mother plant dying: normal after bloom. Brown cup: stagnant water — flush regularly. Root rot: water on the soil, not in the cup.',
  },

  // ─── Nerve Plant & Others ─────────────────────────────────────────────────
  {
    id: 'nerve-plant',
    name: 'Nerve Plant',
    aliases: ['Fittonia', 'Mosaic Plant', 'Silver Nerve Plant'],
    emoji: '🔴',
    baseIntervalDays: 3,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Low to medium indirect light. One of the best plants for terrariums.',
    watering: 'Keep consistently moist. Wilts dramatically when dry but recovers quickly after watering (known as the "fainting" plant).',
    fertilising: 'Monthly spring/summer at quarter strength.',
    seasonal: 'Melbourne: best kept in a terrarium or cloche to maintain humidity. Reduce watering slightly in winter.',
    commonProblems: 'Sudden collapse (fainting): thirsty — water immediately, recovers within an hour. Brown edges: low humidity. Legginess: trim regularly for bushy growth.',
  },
  {
    id: 'african-violet',
    name: 'African Violet',
    aliases: ['Saintpaulia', 'Saintpaulia ionantha'],
    emoji: '💜',
    baseIntervalDays: 5,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: false,
    light: 'Bright indirect light — a north-facing window is ideal. Light is critical for continuous blooming.',
    watering: 'Water from below by sitting the pot in a saucer of water for 30 minutes. Never wet the leaves — causes brown spots. Keep slightly moist.',
    fertilising: 'Monthly with African Violet fertiliser (high phosphorus for continuous blooming).',
    seasonal: 'Melbourne: blooms almost continuously in the right conditions. Keep away from cold drafts and below 15°C temperatures. Avoid direct sun.',
    commonProblems: 'Brown spots on leaves: water on leaves or cold water. No flowers: insufficient light or needs fertiliser. Root rot: overwatering or wrong soil type — use African Violet mix.',
  },
  {
    id: 'begonia',
    name: 'Begonia',
    aliases: ['Rex Begonia', 'Cane Begonia', 'Wax Begonia', 'Angel Wing Begonia'],
    emoji: '🌺',
    baseIntervalDays: 5,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright indirect light. Most begonias prefer filtered light.',
    watering: 'Keep consistently moist but not waterlogged. Water at the base to avoid powdery mildew on leaves.',
    fertilising: 'Every 2 weeks spring/summer with balanced fertiliser.',
    seasonal: 'Melbourne: cane begonias grow beautifully in sheltered outdoor positions in summer. Tuberous begonias go dormant in winter — store tubers dry. Rex begonias are purely indoor plants.',
    commonProblems: 'Powdery mildew: water on leaves or poor airflow. Root rot: overwatering. Leggy growth: insufficient light.',
  },
  {
    id: 'croton',
    name: 'Croton',
    aliases: ['Codiaeum variegatum', 'Joseph\'s Coat', 'Garden Croton'],
    emoji: '🎨',
    baseIntervalDays: 7,
    difficulty: 'Intermediate',
    humidity: 'Medium',
    toxic: true, toxicTo: 'both',
    light: 'Bright direct to bright indirect light essential — without it, the colourful foliage fades to green.',
    watering: 'Water when top 2–3cm is dry. Consistent moisture preferred. Dramatic drooper when thirsty.',
    fertilising: 'Monthly spring/summer.',
    seasonal: 'Melbourne: keep indoors in a bright spot. Outdoors in sheltered summer position. Sensitive to cold and drafts — drops leaves when stressed.',
    commonProblems: 'Leaf drop: moved the plant, drafts, or temperature shock. Fading colours: insufficient light — needs very bright light or direct morning sun. Spider mites: very common in dry conditions.',
  },

  // ─── Geranium & Seasonals ─────────────────────────────────────────────────
  {
    id: 'geranium',
    name: 'Geranium',
    aliases: ['Pelargonium', 'Zonal Geranium', 'Scented Geranium'],
    emoji: '🌸',
    baseIntervalDays: 5,
    difficulty: 'Beginner',
    humidity: 'Low',
    toxic: true, toxicTo: 'pets',
    light: 'Full sun — at least 4–6 hours of direct sun.',
    watering: 'Water when top 3–4cm is dry. Allow soil to slightly dry between waterings — very drought tolerant once established.',
    fertilising: 'Every 2 weeks spring/summer with high-potassium fertiliser to promote flowering.',
    seasonal: 'Melbourne: grow outdoors in full sun. Deadhead regularly for continuous blooms. In winter, cut back by half and reduce watering. Rewarding Melbourne balcony and garden plant.',
    commonProblems: 'Root rot: overwatering. No flowers: insufficient sun or phosphorus/potassium. Edema (corky bumps on leaves): inconsistent watering.',
  },

  // ─── Venus Fly Trap & Carnivores ─────────────────────────────────────────
  {
    id: 'venus-fly-trap',
    name: 'Venus Fly Trap',
    aliases: ['Dionaea muscipula', 'VFT'],
    emoji: '🪤',
    baseIntervalDays: 3,
    difficulty: 'Advanced',
    humidity: 'High',
    toxic: false,
    light: 'Full sun — at least 4–6 hours of direct sun essential.',
    watering: 'Use ONLY distilled water or rainwater — tap water kills it. Sit in a tray of 1–2cm of water at all times (tray method). Never let it dry out.',
    fertilising: 'Never fertilise — it gets nutrients from insects. Feeding once per month with a small live bug is beneficial.',
    seasonal: 'Melbourne: goes dormant in winter (May–August). Leaves may die back completely — this is normal. Reduce watering slightly but don\'t let it dry. New growth emerges in spring.',
    commonProblems: 'Death: tap water minerals/fluoride. Blackening traps: natural after each trap fires 3–5 times. Dormancy: normal winter behaviour — don\'t discard.',
  },
  {
    id: 'pitcher-plant',
    name: 'Pitcher Plant',
    aliases: ['Sarracenia', 'North American Pitcher Plant', 'Trumpet Pitcher'],
    emoji: '🏺',
    baseIntervalDays: 3,
    difficulty: 'Intermediate',
    humidity: 'High',
    toxic: false,
    light: 'Full sun — minimum 4 hours of direct sun.',
    watering: 'Sit in 2–3cm of distilled water or rainwater at all times. Never tap water.',
    fertilising: 'Never fertilise — gets nutrients from trapped insects.',
    seasonal: 'Melbourne: outdoor plant in Melbourne\'s climate — tolerates frost. Goes dormant in winter (dies back). Regrows in spring. A tough and fascinating plant.',
    commonProblems: 'Pitchers not forming: insufficient sun. Death: tap water. Dormancy: completely normal in autumn/winter.',
  },
]

export function searchSpecies(query: string): SpeciesProfile[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return SPECIES_DB.filter(
    s =>
      s.name.toLowerCase().includes(q) ||
      s.aliases.some(a => a.toLowerCase().includes(q)),
  ).slice(0, 20)
}

export function getSpeciesById(id: string): SpeciesProfile | undefined {
  return SPECIES_DB.find(s => s.id === id)
}

export function getSpeciesByDifficulty(
  level: SpeciesProfile['difficulty'],
): SpeciesProfile[] {
  return SPECIES_DB.filter(s => s.difficulty === level)
}
